"""
Church Devotional Generator for BelieversFlow
Generates 365 devotionals for each of 12 denominations.
"""
import os

def js_escape(s):
    return (s.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
            .replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t'))

# Each denomination: name, pastor, color, focus, and 50 core (title, verse, verse_text) tuples
# The generator cycles through these to produce 365 days
DENOMINATIONS = {
    "dunamis": {
        "name": "Dunamis Gospel Church", "pastor": "Pastor Paul Enenche", "color": "#8B0000",
        "focus": "Holy Spirit power, divine health, anointing",
        "themes": [
            ("The Power of the Holy Spirit", "Acts 1:8", "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me."),
            ("Walking in Divine Health", "3 John 1:2", "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth."),
            ("The Anointing Breaks Yokes", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Financial Overflow", "Deuteronomy 8:18", "It is he that giveth thee power to get wealth."),
            ("Divine Direction", "Proverbs 3:5-6", "In all thy ways acknowledge him, and he shall direct thy paths."),
            ("Supernatural Signs", "Mark 16:17", "And these signs shall follow them that believe."),
            ("Restoration of All Things", "Acts 3:21", "Whom the heaven must receive until the times of restitution of all things."),
            ("The Fire of God", "Hebrews 12:29", "For our God is a consuming fire."),
            ("Power for Witnessing", "Acts 1:8", "Ye shall receive power when the Holy Ghost is come upon you."),
            ("The Gift of Healing", "Isaiah 53:5", "With his stripes we are healed."),
            ("Divine Provision", "Philippians 4:19", "My God shall supply all your need according to his riches in glory."),
            ("Spiritual Authority", "Luke 10:19", "I give unto you power to tread on serpents and scorpions."),
            ("The Blood of Jesus", "Revelation 12:11", "They overcame him by the blood of the Lamb."),
            ("Prayer as a Weapon", "Ephesians 6:18", "Praying always with all prayer and supplication in the Spirit."),
            ("The Word of Power", "Isaiah 55:11", "My word shall not return unto me void."),
            ("Faith that Conquers", "Mark 11:22", "Have faith in God."),
            ("The Anointing of Success", "2 Corinthians 1:21", "God hath anointed us."),
            ("Breakthrough Prayers", "Matthew 17:20", "If ye have faith as a grain of mustard seed."),
            ("Divine Favor", "Psalm 5:12", "Thou wilt bless the righteous with favour."),
            ("The Holy Spirit's Guidance", "John 16:13", "He will guide you into all truth."),
            ("Walking in Miracles", "Acts 2:22", "Jesus of Nazareth, a man approved of God by miracles and wonders."),
            ("The Power of Praise", "Psalm 150:6", "Let everything that hath breath praise the Lord."),
            ("Spiritual Warfare", "2 Corinthians 10:4", "The weapons of our warfare are not carnal."),
            ("Divine Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("The Covenant of Health", "Exodus 15:26", "I am the Lord that healeth thee."),
            ("Power in the Name of Jesus", "Philippians 2:9-11", "God gave him a name which is above every name."),
            ("The Gift of Wisdom", "James 1:5", "Let him ask of God, that giveth to all men liberally."),
            ("Supernatural Increase", "Haggai 2:8", "The silver is mine, and the gold is mine."),
            ("The Anointing to Prosper", "Zechariah 4:6", "Not by might, nor by power, but by my spirit."),
            ("Divine Healing", "1 Peter 2:24", "By whose stripes ye were healed."),
            ("The Power of Testimony", "Revelation 12:11", "They overcame by the word of their testimony."),
            ("The Holy Spirit's Fire", "Acts 2:3", "There appeared unto them cloven tongues like as of fire."),
            ("Breakthrough in Prayer", "Jeremiah 33:3", "Call unto me, and I will answer thee."),
            ("Divine Open Doors", "Revelation 3:8", "I have set before thee an open door."),
            ("Power Over Darkness", "Colossians 1:13", "He hath delivered us from the power of darkness."),
            ("The Gift of Faith", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Divine Restoration", "Joel 2:25", "I will restore to you the years that the locust hath eaten."),
            ("The Power of Worship", "John 4:24", "They that worship him must worship him in spirit and truth."),
            ("Spiritual Gifts", "1 Corinthians 12:4-7", "There are diversities of gifts, but the same Spirit."),
            ("The Anointing of Prosperity", "Deuteronomy 28:2", "All these blessings shall come on thee and overtake thee."),
            ("Divine Connections", "Proverbs 27:17", "Iron sharpeneth iron."),
            ("The Power of Decree", "Job 22:28", "Thou shalt decree a thing, and it shall be established."),
            ("Walking in Signs", "Mark 16:17", "These signs shall follow them that believe."),
            ("Breakthrough in Fasting", "Matthew 17:21", "This kind goeth not out but by prayer and fasting."),
            ("Divine Elevation", "Psalm 75:6-7", "Promotion cometh from the Lord."),
            ("The Anointing of Healing", "James 5:14", "Let them pray over him, anointing him with oil."),
            ("Power in the Blood", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("The Gift of Prophecy", "1 Corinthians 14:1", "Desire spiritual gifts, but rather that ye may prophesy."),
            ("Divine Abundance", "John 10:10", "I am come that they might have life more abundantly."),
            ("The Power of Thanksgiving", "Psalm 100:4", "Enter into his gates with thanksgiving."),
        ],
    },
    "rccg": {
        "name": "Redeemed Christian Church of God", "pastor": "Pastor E.A. Adeboye", "color": "#FF0000",
        "focus": "Open heavens, divine protection, covenant blessings",
        "themes": [
            ("Heavenly Blessings", "Ephesians 1:3", "God hath blessed us with all spiritual blessings in heavenly places."),
            ("The Open Heavens", "Malachi 3:10", "I will open you the windows of heaven and pour you out a blessing."),
            ("Divine Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty."),
            ("The Blood of Jesus", "Revelation 12:11", "They overcame him by the blood of the Lamb."),
            ("Restoration", "Joel 2:25", "I will restore to you the years that the locust hath eaten."),
            ("The Holy Spirit's Guidance", "John 16:13", "He will guide you into all truth."),
            ("Victory in Christ", "1 Corinthians 15:57", "Thanks be to God which giveth us the victory."),
            ("Covenant of Blessing", "Genesis 12:2", "I will make of thee a great nation, and I will bless thee."),
            ("Divine Healing", "Isaiah 53:5", "With his stripes we are healed."),
            ("The Power of Prayer", "James 5:16", "The effectual fervent prayer of a righteous man availeth much."),
            ("Heavenly Intelligence", "Daniel 2:22", "He revealeth deep and secret things."),
            ("Divine Provision", "Philippians 4:19", "My God shall supply all your need."),
            ("The Anointing", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Favour of God", "Psalm 5:12", "Thou wilt bless the righteous with favour."),
            ("Breakthrough", "Micah 2:13", "The breaker is come up before them."),
            ("Divine Direction", "Proverbs 3:5-6", "He shall direct thy paths."),
            ("The Power of Praise", "2 Chronicles 5:13", "The house was filled with a cloud."),
            ("God's Faithfulness", "Lamentations 3:22-23", "His compassions are new every morning."),
            ("Spiritual Growth", "2 Peter 3:18", "Grow in grace and knowledge."),
            ("The Word of God", "Hebrews 4:12", "The word of God is quick and powerful."),
            ("Divine Speed", "Habakkuk 2:2-3", "Write the vision and make it plain."),
            ("The Power of Agreement", "Matthew 18:19", "If two shall agree on earth."),
            ("God's Promises", "2 Corinthians 1:20", "All the promises of God are yea and amen."),
            ("Divine Overflow", "Malachi 3:10", "Pour you out a blessing that there shall not be room enough."),
            ("The Gift of the Holy Spirit", "Acts 1:8", "Ye shall receive power when the Holy Ghost is come."),
            ("Walking in Truth", "3 John 1:4", "I have no greater joy than to hear that my children walk in truth."),
            ("Divine Opportunity", "Revelation 3:8", "I have set before thee an open door."),
            ("The Power of Seeds", "Galatians 6:7", "Whatsoever a man soweth, that shall he also reap."),
            ("God's Sufficient Grace", "2 Corinthians 12:9", "My grace is sufficient for thee."),
            ("Divine Settlement", "Jeremiah 29:11", "I know the thoughts that I think toward you, thoughts of peace."),
            ("The Power of Thanksgiving", "Psalm 100:4", "Enter into his gates with thanksgiving."),
            ("Walking in Dominion", "Genesis 1:28", "Be fruitful, multiply, replenish the earth, and subdue it."),
            ("The Anointing of Prosperity", "Deuteronomy 28:2", "All these blessings shall come on thee."),
            ("Divine Preservation", "Psalm 121:7", "The Lord shall preserve thee from all evil."),
            ("The Power of Worship", "John 4:24", "Worship him in spirit and truth."),
            ("God's Unfailing Love", "Psalm 136:26", "His steadfast love endures forever."),
            ("Divine Help", "Psalm 121:1-2", "My help cometh from the Lord."),
            ("The Power of the Word", "Isaiah 55:11", "My word shall accomplish what I please."),
            ("Covenant of Peace", "Ezekiel 37:26", "I will make a covenant of peace with them."),
            ("Divine Favor", "Psalm 30:5", "His favor is for life."),
            ("The Power of Testimony", "Revelation 12:11", "They overcame by the word of their testimony."),
            ("God's Protective Cover", "Psalm 91:4", "He shall cover thee with his feathers."),
            ("Divine Open Heavens", "Malachi 3:10", "I will open you the windows of heaven."),
            ("The Anointing of Breakthrough", "Isaiah 10:27", "The yoke shall be destroyed."),
            ("Walking in Victory", "Romans 8:37", "We are more than conquerors."),
            ("Divine Abundance", "John 10:10", "Life more abundantly."),
            ("The Power of Faith", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Covenant of Prosperity", "Deuteronomy 8:18", "He giveth thee power to get wealth."),
            ("Divine Elevation", "Psalm 75:6-7", "Promotion cometh from the Lord."),
            ("The Power of Intercession", "Ezekiel 22:30", "I sought for a man to stand in the gap."),
        ],
    },
    "mfm": {
        "name": "Mountain of Fire and Miracles Ministries", "pastor": "Dr. D.K. Olukoya", "color": "#800080",
        "focus": "Prayer, warfare, deliverance, fire",
        "themes": [
            ("Prayer as a Weapon", "Ephesians 6:18", "Praying always with all prayer and supplication in the Spirit."),
            ("Spiritual Warfare", "2 Corinthians 10:4", "The weapons of our warfare are not carnal."),
            ("Breaking Curses", "Galatians 3:13", "Christ hath redeemed us from the curse of the law."),
            ("The Fire of God", "Hebrews 12:29", "Our God is a consuming fire."),
            ("Deliverance from Evil", "Psalm 91:3", "He shall deliver thee from the snare of the fowler."),
            ("The Anointing to Overcome", "1 John 2:27", "The anointing which ye have received abideth in you."),
            ("Miracles and Signs", "Acts 2:22", "Jesus of Nazareth, approved of God by miracles and wonders."),
            ("Power in the Blood", "Revelation 12:11", "They overcame by the blood of the Lamb."),
            ("Breaking Generational Curses", "Exodus 20:5", "Visiting the iniquity of the fathers upon the children."),
            ("The Power of Decrees", "Job 22:28", "Thou shalt decree a thing, and it shall be established."),
            ("Spiritual Mapping", "2 Kings 6:12", "The Lord hath opened his eyes."),
            ("Territorial Powers", "Daniel 10:13", "The prince of the kingdom of Persia withstood me."),
            ("The Fire of the Holy Ghost", "Acts 2:3", "Cloven tongues like as of fire sat upon each of them."),
            ("Breaking Yokes", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Warfare Prayers", "1 Timothy 1:18", "War a good warfare."),
            ("The Blood of Jesus", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("Deliverance Ministry", "Luke 4:18", "He hath sent me to deliver the captives."),
            ("Spiritual Gifts", "1 Corinthians 12:10", "To another discerning of spirits."),
            ("Breaking Bondages", "Isaiah 61:1", "The Lord hath anointed me to loose the captives."),
            ("The Name of Jesus", "Philippians 2:9-11", "God gave him a name above every name."),
            ("Prayer Fasting", "Matthew 17:21", "This kind goeth not out but by prayer and fasting."),
            ("Spiritual Eyes", "2 Kings 6:17", "Lord, I pray thee, open his eyes that he may see."),
            ("The Fire Test", "1 Peter 1:7", "The trial of your faith being much more precious than gold."),
            ("Breaking Satanic Chains", "Psalm 107:14", "He brought them out of darkness and the shadow of death."),
            ("The Anointing Breaks Yokes", "Isaiah 10:27", "The yoke shall be destroyed."),
            ("Power in Prayer", "James 5:16", "The effectual fervent prayer availeth much."),
            ("Spiritual Warfare Strategy", "Ephesians 6:11", "Put on the whole armour of God."),
            ("Breaking Witchcraft", "Galatians 5:1", "Stand fast therefore in the liberty."),
            ("The Fire of Revival", "Acts 2:3", "Tongues of fire sat upon each of them."),
            ("Deliverance Prayers", "Psalm 91:3", "He shall deliver thee from the snare."),
            ("Breaking Poverty", "Deuteronomy 28:47-48", "Because thou didst not serve the Lord with joyfulness."),
            ("The Blood Covenant", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("Spiritual Monitoring", "2 Kings 6:12", "The Lord hath opened his eyes."),
            ("Breaking Barriers", "Isaiah 54:2", "Enlarge the place of thy tent."),
            ("The Anointing of Fire", "Malachi 3:2", "He shall sit as a refiner and purifier of silver."),
            ("Breaking Evil Patterns", "Romans 12:2", "Be transformed by the renewing of your mind."),
            ("Power in the Word", "Hebrews 4:12", "The word of God is quick and powerful."),
            ("Deliverance from Oppression", "Psalm 107:14", "He brought them out of darkness."),
            ("The Fire of God's Presence", "Exodus 3:2", "The bush burned with fire and was not consumed."),
            ("Breaking Addiction", "John 8:36", "If the Son shall make you free, ye shall be free indeed."),
            ("Spiritual Authority", "Luke 10:19", "I give you power to tread on serpents."),
            ("Breaking Sickness", "Isaiah 53:5", "By his stripes we are healed."),
            ("The Blood of Sprinkling", "Hebrews 12:24", "The blood of sprinkling that speaketh better things."),
            ("Breaking Failure", "Deuteronomy 28:13", "The Lord shall make thee the head and not the tail."),
            ("The Fire of Judgment", "Malachi 3:2", "Who shall abide the day of his coming?"),
            ("Breaking Delay", "Habakkuk 2:3", "Though it tarry, wait for it."),
            ("Spiritual Intelligence", "Daniel 2:22", "He revealeth deep and secret things."),
            ("Breaking Shame", "Isaiah 54:4", "Fear not, for thou shalt not be ashamed."),
            ("The Anointing of Fire", "Acts 2:3", "Tongues of fire sat upon each of them."),
        ],
    },
    "deeperlife": {
        "name": "Deeper Life Bible Church", "pastor": "Pastor W.F. Kumuyi", "color": "#0000CD",
        "focus": "Holiness, obedience, word of God",
        "themes": [
            ("Holiness and Purity", "Hebrews 12:14", "Follow peace with all men, and holiness, without which no man shall see the Lord."),
            ("The Power of the Blood", "Leviticus 17:11", "The life of the flesh is in the blood."),
            ("Obedience to God", "John 14:15", "If ye love me, keep my commandments."),
            ("The Word of God", "Psalm 119:105", "Thy word is a lamp to my feet."),
            ("Prayer and Fasting", "Matthew 17:21", "This kind goeth not out but by prayer and fasting."),
            ("Spiritual Growth", "2 Peter 3:18", "Grow in grace and knowledge."),
            ("Faithfulness in Service", "Matthew 25:21", "Well done, thou good and faithful servant."),
            ("The Fear of the Lord", "Proverbs 9:10", "The fear of the Lord is the beginning of wisdom."),
            ("Walking in Obedience", "Deuteronomy 28:1", "If thou shalt hearken diligently unto the voice of the Lord."),
            ("Purity of Heart", "Matthew 5:8", "Blessed are the pure in heart, for they shall see God."),
            ("The Scripture", "2 Timothy 3:16-17", "All Scripture is God-breathed and is useful for teaching."),
            ("Holy Living", "1 Peter 1:15-16", "Be holy in all you do; for it is written, Be holy because I am holy."),
            ("Prayer Life", "1 Thessalonians 5:17", "Pray without ceasing."),
            ("The Fear of Sin", "Proverbs 8:13", "The fear of the Lord is to hate evil."),
            ("Daily Devotion", "Psalm 1:2", "His delight is in the law of the Lord."),
            ("Spiritual Discipline", "1 Corinthians 9:27", "I discipline my body and keep it under control."),
            ("The Bible", "Psalm 119:160", "The sum of your word is truth."),
            ("God's Commandments", "1 John 5:3", "This is love for God: to keep his commands."),
            ("Moral Integrity", "Proverbs 10:9", "Whoever walks in integrity walks securely."),
            ("Separation from World", "Romans 12:2", "Do not conform to the pattern of this world."),
            ("Biblical Doctrine", "Titus 2:1", "Teach what is in accord with sound doctrine."),
            ("Prayer and Meditation", "Psalm 1:2", "On his law he meditates day and night."),
            ("Holy Spirit Leadership", "Romans 8:14", "Those who are led by the Spirit of God are the children of God."),
            ("The Fear of God", "Proverbs 14:27", "The fear of the Lord is a fountain of life."),
            ("Righteous Living", "Psalm 23:3", "He leads me in paths of righteousness for his name sake."),
            ("Spiritual Maturity", "Hebrews 6:1", "Let us go on to maturity."),
            ("Obedience and Blessing", "Deuteronomy 28:2", "All these blessings shall come on you."),
            ("The Power of God's Word", "Hebrews 4:12", "The word of God is alive and active."),
            ("Godly Wisdom", "James 3:17", "The wisdom that comes from heaven is pure."),
            ("Walking with God", "Amos 3:3", "Can two walk together unless they are agreed?"),
            ("Purity in Action", "James 1:27", "Keep oneself from being polluted by the world."),
            ("Biblical Fasting", "Isaiah 58:6", "Is not this the fast that I have chosen?"),
            ("Scripture Memory", "Psalm 119:11", "I have hidden your word in my heart."),
            ("Godly Character", "Galatians 5:22-23", "The fruit of the Spirit is love, joy, peace."),
            ("Spiritual Warfare", "Ephesians 6:10-11", "Be strong in the Lord and in his mighty power."),
            ("Prayer of Faith", "James 5:15", "The prayer offered in faith will make the sick person well."),
            ("The Holy Spirit", "John 14:26", "The Holy Spirit will teach you all things."),
            ("God's Will", "Romans 12:2", "Be transformed by the renewing of your mind."),
            ("Divine Health", "3 John 1:2", "I wish that you may prosper and be in health."),
            ("Financial Stewardship", "Malachi 3:10", "Bring the whole tithe into the storehouse."),
            ("The Power of Worship", "John 4:24", "Worship in spirit and truth."),
            ("God's Forgiveness", "1 John 1:9", "He is faithful and just to forgive us our sins."),
            ("The Cross of Christ", "Galatians 6:14", "May I never boast except in the cross of our Lord."),
            ("Resurrection Power", "Philippians 3:10", "I want to know Christ and the power of his resurrection."),
            ("Eternal Life", "John 3:16", "Whoever believes in him shall not perish but have eternal life."),
            ("The Second Coming", "Revelation 22:12", "I am coming soon."),
            ("Heavenly Reward", "Matthew 6:20", "Store up for yourselves treasures in heaven."),
            ("Serving Others", "Galatians 5:13", "Serve one another humbly in love."),
            ("Church Fellowship", "Hebrews 10:25", "Not forsaking the assembling of ourselves together."),
            ("Evangelism", "Matthew 28:19", "Go and make disciples of all nations."),
        ],
    },
    "believersloveworld": {
        "name": "Believers Loveworld (Christ Embassy)", "pastor": "Pastor Chris Oyakhilome", "color": "#FFD700",
        "focus": "Word of God, identity in Christ, faith",
        "themes": [
            ("You Are Born of the Word", "1 Peter 1:23", "Being born again, not of corruptible seed, but of incorruptible, by the word of God."),
            ("The Spirit of God in You", "1 Corinthians 3:16", "Ye are the temple of God, and the Spirit of God dwelleth in you."),
            ("Walking in Love", "1 John 4:8", "He that loveth not knoweth not God; for God is love."),
            ("The Power of Faith", "Mark 11:22", "Have faith in God."),
            ("Your Identity in Christ", "2 Corinthians 5:17", "If any man be in Christ, he is a new creature."),
            ("The Anointing of the Holy Spirit", "Acts 10:38", "God anointed Jesus of Nazareth with the Holy Ghost and with power."),
            ("Glorifying God", "1 Corinthians 10:31", "Whether therefore ye eat, or drink, do all to the glory of God."),
            ("The Word as Medicine", "Proverbs 4:22", "They are life to those who find them and health to one's whole body."),
            ("Righteousness Consciousness", "2 Corinthians 5:21", "God made him who had no sin to be sin for us."),
            ("The Love of God", "Romans 8:38-39", "Nothing can separate us from the love of God."),
            ("Walking in the Spirit", "Galatians 5:16", "Walk by the Spirit, and you will not gratify the desires of the flesh."),
            ("The Power of Words", "Proverbs 18:21", "The tongue has the power of life and death."),
            ("Divine Healing", "Isaiah 53:5", "By his stripes we are healed."),
            ("The Holy Spirit", "John 14:16", "He will give you another advocate to help you."),
            ("Faith Speaks", "2 Corinthians 4:13", "I believed; therefore I have spoken."),
            ("Your Redemption", "Ephesians 1:7", "In him we have redemption through his blood."),
            ("The Word of Power", "Hebrews 4:12", "The word of God is alive and active."),
            ("Divine Prosperity", "3 John 1:2", "I wish that you may prosper and be in health."),
            ("The Holy Spirit's Ministry", "John 16:13", "He will guide you into all truth."),
            ("New Creation Reality", "2 Corinthians 5:17", "The new creation has come: The old has gone, the new is here."),
            ("The Power of Praise", "Psalm 150:6", "Let everything that breathes praise the Lord."),
            ("Walking in Victory", "1 John 5:4", "Everyone born of God overcomes the world."),
            ("The Anointing", "1 John 2:27", "The anointing you received from him remains in you."),
            ("Divine Guidance", "Proverbs 3:5-6", "He will make your paths straight."),
            ("The Blood Covenant", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("Spiritual Authority", "Luke 10:19", "I have given you authority over all the power of the enemy."),
            ("The Power of Confession", "Romans 10:10", "It is with your heart that you believe and are justified."),
            ("Divine Protection", "Psalm 91:1", "He who dwells in the shelter of the Most High."),
            ("The Word of God", "John 1:1", "The Word was with God, and the Word was God."),
            ("Walking in Grace", "2 Corinthians 12:9", "My grace is sufficient for you."),
            ("The Power of Love", "1 Corinthians 13:4-7", "Love is patient, love is kind."),
            ("Your Heritage", "1 Peter 2:9", "You are a chosen people, a royal priesthood."),
            ("Divine Health", "Exodus 15:26", "I am the Lord who heals you."),
            ("The Power of Faith", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Walking in Righteousness", "1 John 2:29", "Everyone who does what is right is born of him."),
            ("The Holy Spirit's Power", "Acts 1:8", "You will receive power when the Holy Spirit comes."),
            ("Divine Abundance", "John 10:10", "I have come that they may have life abundantly."),
            ("The Word of Faith", "Romans 10:8", "The word is near you; it is in your mouth and in your heart."),
            ("Walking in Light", "1 John 1:7", "If we walk in the light, as he is in the light."),
            ("The Power of Worship", "John 4:24", "Worship in spirit and truth."),
            ("Your Identity", "Ephesians 2:10", "We are God's handiwork, created in Christ Jesus."),
            ("Divine Favor", "Psalm 5:12", "The Lord blesses the righteous with favor."),
            ("The Word of Life", "Philippians 2:16", "Holding fast to the word of life."),
            ("Walking in Peace", "John 14:27", "My peace I give you."),
            ("The Power of Thanksgiving", "Psalm 100:4", "Enter his gates with thanksgiving."),
            ("Your Inheritance", "Ephesians 1:11", "We have been chosen as a inheritance."),
            ("Divine Open Doors", "Revelation 3:8", "I have set before you an open door."),
            ("The Power of the Word", "Isaiah 55:11", "My word will accomplish what I desire."),
            ("Walking in Joy", "Nehemiah 8:10", "The joy of the Lord is your strength."),
            ("The Anointing Breaks Yokes", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
        ],
    },
    "fcs": {
        "name": "Fellowship of Christian Students", "pastor": "FCS Leadership", "color": "#006400",
        "focus": "Student life, academics, peer pressure",
        "themes": [
            ("Standing Firm in Faith", "1 Corinthians 16:13", "Watch ye, stand fast in the faith, quit you like men, be strong."),
            ("Academic Excellence", "Colossians 3:23", "Whatsoever ye do, do it heartily, as to the Lord."),
            ("Peer Pressure and God's Standard", "Romans 12:2", "Be not conformed to this world, but be transformed."),
            ("Prayer as Students", "Philippians 4:6", "Be careful for nothing; but in every thing by prayer."),
            ("The Power of Fellowship", "Hebrews 10:25", "Not forsaking the assembling of ourselves together."),
            ("Integrity in Academics", "Proverbs 11:3", "The integrity of the upright shall guide them."),
            ("Purpose Beyond Campus", "Jeremiah 29:11", "I know the thoughts that I think toward you."),
            ("Time Management", "Ephesians 5:15-16", "Redeeming the time, because the days are evil."),
            ("Study as Worship", "Proverbs 22:6", "Train up a child in the way he should go."),
            ("Godly Relationships", "1 Corinthians 15:33", "Be not deceived: evil communications corrupt good manners."),
            ("Exam Success", "James 1:5", "If any of you lack wisdom, let him ask of God."),
            ("Campus Evangelism", "Matthew 28:19", "Go ye therefore and teach all nations."),
            ("Dealing with Stress", "Matthew 11:28", "Come unto me, all ye that labour and are heavy laden."),
            ("Scholarship and Provision", "Philippians 4:19", "My God shall supply all your need."),
            ("Spiritual Disciplines", "1 Timothy 4:15", "Meditate upon these things; give thyself wholly to them."),
            ("Resisting Temptation", "1 Corinthians 10:13", "God is faithful, who will not suffer you to be tempted above that ye are able."),
            ("Godly Ambition", "Proverbs 16:3", "Commit thy works unto the Lord, and thy thoughts shall be established."),
            ("Mentorship", "Proverbs 27:17", "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend."),
            ("Campus Ministry", "Matthew 5:16", "Let your light so shine before men."),
            ("Study Habits", "Proverbs 4:7", "Wisdom is the principal thing; therefore get wisdom."),
            ("Academic Integrity", "Proverbs 12:22", "Lying lips are an abomination to the Lord."),
            ("Student Prayer Life", "1 Thessalonians 5:17", "Pray without ceasing."),
            ("Dealing with Failure", "Proverbs 24:16", "For a just man falleth seven times, and riseth up again."),
            ("Godly Study Partners", "Ecclesiastes 4:9-10", "Two are better than one."),
            ("Balancing Studies and Faith", "Matthew 6:33", "Seek ye first the kingdom of God."),
            ("Campus Safety", "Psalm 121:7", "The Lord shall preserve thee from all evil."),
            ("Exam Preparation", "Proverbs 21:5", "The thoughts of the diligent tend only to plenteousness."),
            ("Academic Honesty", "Colossians 3:9", "Lie not one to another."),
            ("Student Leadership", "1 Timothy 4:12", "Be thou an example of the believers."),
            ("Campus Community", "John 13:35", "By this shall all men know that ye are my disciples."),
            ("Spiritual Gifts", "1 Corinthians 12:7", "The manifestation of the Spirit is given to every man."),
            ("Student Finances", "Proverbs 3:9", "Honour the Lord with thy substance."),
            ("Campus Ministry", "Romans 1:16", "I am not ashamed of the gospel."),
            ("Dealing with Loneliness", "Hebrews 13:5", "I will never leave thee, nor forsake thee."),
            ("Godly Friendships", "Proverbs 18:24", "There is a friend that sticketh closer than a brother."),
            ("Campus Evangelism", "Mark 16:15", "Go ye into all the world, and preach the gospel."),
            ("Study Motivation", "Colossians 3:23", "Do it heartily, as to the Lord."),
            ("Academic Challenges", "James 1:2", "Count it all joy when you fall into various trials."),
            ("Student Prayer", "Jeremiah 33:3", "Call unto me, and I will answer thee."),
            ("Campus Worship", "Psalm 100:4", "Enter into his gates with thanksgiving."),
            ("Student Fellowship", "Acts 2:46", "They continued daily with one accord."),
            ("Academic Goals", "Philippians 3:14", "I press toward the mark for the prize."),
            ("Dealing with Criticism", "Proverbs 15:1", "A soft answer turneth away wrath."),
            ("Godly Study Habits", "Joshua 1:8", "Meditate therein day and night."),
            ("Campus Revival", "Acts 2:17", "I will pour out my Spirit upon all flesh."),
            ("Student Ministry", "1 Timothy 4:12", "Be an example in word, in conversation, in spirit."),
            ("Academic Success", "Proverbs 2:6", "The Lord giveth wisdom."),
            ("Campus Unity", "John 17:21", "That they all may be one."),
            ("Student Purpose", "Ephesians 2:10", "Created in Christ Jesus unto good works."),
        ],
    },
    "foodfortheday": {
        "name": "Food for the Day", "pastor": "Various Authors", "color": "#FF8C00",
        "focus": "Daily provision, spiritual nourishment",
        "themes": [
            ("Daily Bread from Heaven", "John 6:35", "I am the bread of life: he that cometh to me shall never hunger."),
            ("Manna for Today", "Exodus 16:4", "I will rain bread from heaven for you."),
            ("The Word as Food", "Matthew 4:4", "Man shall not live by bread alone, but by every word."),
            ("Feeding Others", "Matthew 25:35", "I was an hungred, and ye gave me meat."),
            ("Spiritual Fasting", "Isaiah 58:6", "Is not this the fast that I have chosen?"),
            ("Bread of Affliction", "Psalm 127:2", "He giveth his beloved sleep."),
            ("The Table of the Lord", "Psalm 23:5", "Thou preparest a table before me."),
            ("Daily Nourishment", "Psalm 119:103", "How sweet are thy words unto my taste."),
            ("Spiritual Hunger", "Matthew 5:6", "Blessed are they which do hunger and thirst after righteousness."),
            ("Feeding the Flock", "1 Peter 5:2", "Feed the flock of God which is among you."),
            ("The Bread of Life", "John 6:35", "I am the bread of life."),
            ("Daily Provision", "Matthew 6:11", "Give us this day our daily bread."),
            ("Spiritual Feasting", "Psalm 36:8", "They shall be abundantly satisfied with the fatness of thy house."),
            ("Breaking Bread", "Acts 2:46", "They broke bread in their homes and ate together."),
            ("The Lord's Supper", "1 Corinthians 11:24", "This is my body, which is for you."),
            ("Hungry for God", "Psalm 42:1", "As the hart panteth after the water brooks."),
            ("Feeding the Poor", "Proverbs 19:17", "He that hath pity upon the poor lendeth unto the Lord."),
            ("Daily Strength", "Isaiah 40:31", "They that wait upon the Lord shall renew their strength."),
            ("Spiritual Sustenance", "John 4:14", "The water I give will become a spring of water."),
            ("The Feast of the Lord", "Leviticus 23:4", "These are the feasts of the Lord."),
            ("Feeding the Hungry", "Isaiah 58:10", "If thou pour out thy soul to the hungry."),
            ("Daily Manna", "Exodus 16:15", "It is manna: for they wist not what it was."),
            ("The Word Satisfies", "Jeremiah 15:16", "Thy words were found, and I did eat them."),
            ("Feeding the Spirit", "Galatians 6:8", "He that soweth to the Spirit shall of the Spirit reap life everlasting."),
            ("The Bread of God", "John 6:33", "The bread of God is he which cometh down from heaven."),
            ("Daily Grace", "2 Corinthians 12:9", "My grace is sufficient for thee."),
            ("Feeding the Mind", "Philippians 4:8", "Whatsoever things are true, honest, just, pure, lovely."),
            ("The Bread of Affliction", "Isaiah 30:20", "Though the Lord give you the bread of adversity."),
            ("Feeding the Heart", "Psalm 19:8", "The statutes of the Lord are right, rejoicing the heart."),
            ("Daily Wisdom", "James 1:5", "If any of you lack wisdom, let him ask of God."),
            ("The Table of the Lord", "1 Corinthians 10:21", "Ye cannot drink the cup of the Lord and the cup of devils."),
            ("Feeding the Soul", "Psalm 107:9", "He satisfieth the longing soul."),
            ("Daily Direction", "Proverbs 3:5-6", "In all thy ways acknowledge him, and he shall direct thy paths."),
            ("The Bread of Life", "John 6:48", "I am that bread of life."),
            ("Feeding the Nations", "Matthew 24:14", "This gospel of the kingdom shall be preached in all the world."),
            ("Daily Comfort", "2 Corinthians 1:3-4", "The God of all comfort, who comforts us in all our troubles."),
            ("The Feast of Grace", "Romans 5:15", "The grace of God, and the gift by grace."),
            ("Feeding the Needy", "Matthew 25:35", "I was hungry and you gave me food."),
            ("Daily Protection", "Psalm 121:7", "The Lord shall preserve thee from all evil."),
            ("The Bread of Heaven", "Psalm 78:24", "He had given them of the bread of heaven."),
            ("Feeding the Spirit", "Acts 2:46", "They ate their food with glad and generous hearts."),
            ("Daily Joy", "Nehemiah 8:10", "The joy of the Lord is your strength."),
            ("The Feast of Booths", "Leviticus 23:42", "Ye shall dwell in booths seven days."),
            ("Feeding the Mind", "Romans 12:2", "Be transformed by the renewing of your mind."),
            ("Daily Peace", "John 14:27", "My peace I give to you."),
            ("The Feast of Weeks", "Leviticus 23:16", "You shall present a grain offering of new grain."),
            ("Feeding the Heart", "Colossians 3:16", "Let the word of Christ dwell in you richly."),
            ("Daily Hope", "Romans 15:13", "May the God of hope fill you with all joy and peace."),
            ("The Feast of Trumpets", "Leviticus 23:24", "You shall proclaim a sacred assembly."),
        ],
    },
    "dailymanna": {
        "name": "Daily Manna", "pastor": "Damilola Oyedepo", "color": "#4169E1",
        "focus": "Walking with God, thanksgiving, favor",
        "themes": [
            ("Walking with God", "Amos 3:3", "Can two walk together, except they be agreed?"),
            ("The Power of Thanksgiving", "Psalm 100:4", "Enter into his gates with thanksgiving, and into his courts with praise."),
            ("Divine Favour", "Psalm 5:12", "For thou, Lord, wilt bless the righteous; with favour wilt thou compass him as with a shield."),
            ("Strength in Weakness", "2 Corinthians 12:9", "My grace is sufficient for thee: for my strength is made perfect in weakness."),
            ("The Fear of the Lord", "Proverbs 9:10", "The fear of the Lord is the beginning of wisdom."),
            ("God's Faithfulness", "Lamentations 3:22-23", "It is of the Lord's mercies that we are not consumed, because his compassions fail not. They are new every morning."),
            ("The Joy of the Lord", "Nehemiah 8:10", "The joy of the Lord is your strength."),
            ("Daily Communion", "1 Corinthians 10:16", "The cup of blessing which we bless."),
            ("Walking in Light", "1 John 1:7", "If we walk in the light, as he is in the light."),
            ("Thankful Heart", "Colossians 3:15", "And be ye thankful."),
            ("Divine Guidance", "Proverbs 3:5-6", "In all thy ways acknowledge him, and he shall direct thy paths."),
            ("God's Provision", "Philippians 4:19", "My God shall supply all your need."),
            ("Walking in Love", "1 John 4:7", "Let us love one another: for love is of God."),
            ("Daily Bread", "Matthew 6:11", "Give us this day our daily bread."),
            ("The Peace of God", "Philippians 4:7", "The peace of God, which passeth all understanding."),
            ("Walking by Faith", "2 Corinthians 5:7", "For we walk by faith, not by sight."),
            ("Divine Health", "3 John 1:2", "I wish above all things that thou mayest prosper and be in health."),
            ("The Goodness of God", "Psalm 34:8", "O taste and see that the Lord is good."),
            ("Walking in Wisdom", "Ephesians 5:15", "See then that ye walk circumspectly, not as fools, but as wise."),
            ("Daily Devotion", "Psalm 1:2", "His delight is in the law of the Lord."),
            ("The Lord's Prayer", "Matthew 6:9-13", "Our Father which art in heaven, Hallowed be thy name."),
            ("Walking in Obedience", "John 14:15", "If ye love me, keep my commandments."),
            ("Divine Direction", "Psalm 32:8", "I will instruct thee and teach thee in the way which thou shalt go."),
            ("The Mercies of God", "Lamentations 3:22-23", "His compassions are new every morning."),
            ("Walking in Humility", "Micah 6:8", "To walk humbly with thy God."),
            ("Daily Strength", "Isaiah 40:31", "They that wait upon the Lord shall renew their strength."),
            ("The Presence of God", "Psalm 16:11", "Thou wilt show me the path of life."),
            ("Walking in Righteousness", "Psalm 23:3", "He restoreth my soul: he leadeth me in the paths of righteousness."),
            ("Daily Praise", "Psalm 150:6", "Let everything that hath breath praise the Lord."),
            ("The Love of God", "Romans 8:38-39", "Neither death, nor life, nor angels, nor principalities."),
            ("Walking in Grace", "2 Corinthians 12:9", "My grace is sufficient for thee."),
            ("Daily Forgiveness", "1 John 1:9", "He is faithful and just to forgive us our sins."),
            ("The Power of Prayer", "James 5:16", "The effectual fervent prayer of a righteous man availeth much."),
            ("Walking in Truth", "3 John 1:4", "I have no greater joy than to hear that my children walk in truth."),
            ("Daily Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("The Faithfulness of God", "Deuteronomy 7:9", "Know therefore that the Lord thy God, he is God, the faithful God."),
            ("Walking in Unity", "Ephesians 4:3", "Endeavouring to keep the unity of the Spirit in the bond of peace."),
            ("Daily Deliverance", "Psalm 34:17", "The righteous cry, and the Lord heareth them."),
            ("The Provision of God", "Genesis 22:14", "The Lord will provide."),
            ("Walking in Holiness", "Hebrews 12:14", "Follow peace with all men, and holiness."),
            ("Daily Comfort", "2 Corinthians 1:3-4", "The Father of compassion and the God of all comfort."),
            ("The Power of Worship", "John 4:24", "They that worship him must worship him in spirit and truth."),
            ("Walking in Faith", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Daily Hope", "Romans 15:13", "May the God of hope fill you with all joy and peace."),
            ("The Good Shepherd", "Psalm 23:1", "The Lord is my shepherd; I shall not want."),
            ("Walking in Peace", "John 14:27", "My peace I give to you."),
            ("Daily Grace", "2 Corinthians 12:9", "My grace is sufficient for thee."),
            ("The Anchor of Hope", "Hebrews 6:19", "Which hope we have as an anchor of the soul."),
            ("Walking in Victory", "1 John 5:4", "This is the victory that overcometh the world, even our faith."),
            ("Daily Renewal", "Romans 12:2", "Be ye transformed by the renewing of your mind."),
        ],
    },
    "winners": {
        "name": "Living Faith Church (Winners Chapel)", "pastor": "Bishop David Oyedepo", "color": "#FFD700",
        "focus": "Covenant, faith, breakthrough, prosperity",
        "themes": [
            ("The Covenant of Prosperity", "Deuteronomy 8:18", "It is he that giveth thee power to get wealth."),
            ("Faith that Moves Mountains", "Matthew 17:20", "If ye have faith as a grain of mustard seed."),
            ("The Word as a Weapon", "Hebrews 4:12", "The word of God is quick, and powerful."),
            ("Supernatural Breakthrough", "Exodus 14:21", "The Lord caused the sea to go back by a strong east wind."),
            ("The Anointing for Success", "Zechariah 4:6", "Not by might, nor by power, but by my spirit."),
            ("Dominion Over Challenges", "Genesis 1:28", "Be fruitful, multiply, replenish the earth, and subdue it."),
            ("The Blessing of the Lord", "Proverbs 10:22", "The blessing of the Lord maketh rich."),
            ("Covenant of Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("Faith for Breakthrough", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("The Power of Giving", "Luke 6:38", "Give, and it shall be given unto you."),
            ("Divine Lifting", "Psalm 75:6-7", "Promotion cometh neither from the east, nor from the west."),
            ("Covenant of Abundance", "John 10:10", "I am come that they might have life more abundantly."),
            ("The Word of Faith", "Romans 10:8", "The word is nigh thee, even in thy mouth."),
            ("Supernatural Supply", "Philippians 4:19", "My God shall supply all your need."),
            ("The Anointing of Prosperity", "Deuteronomy 28:2", "All these blessings shall come on thee."),
            ("Faith Action", "James 2:17", "Faith, if it hath not works, is dead."),
            ("Covenant of Health", "Exodus 15:26", "I am the Lord that healeth thee."),
            ("The Power of Decrees", "Job 22:28", "Thou shalt also decree a thing, and it shall be established."),
            ("Dominion Mandate", "Genesis 1:28", "Subdue it: and have dominion."),
            ("Covenant of Open Heavens", "Malachi 3:10", "I will open you the windows of heaven."),
            ("Faith Confession", "Romans 10:9-10", "If thou shalt confess with thy mouth the Lord Jesus."),
            ("The Blessing of Abraham", "Galatians 3:14", "That the blessing of Abraham might come on the Gentiles."),
            ("Supernatural Speed", "Habakkuk 2:2-3", "Write the vision, and make it plain."),
            ("Covenant of Restoration", "Joel 2:25", "I will restore to you the years that the locust hath eaten."),
            ("The Power of Tithing", "Malachi 3:10", "Bring ye all the tithes into the storehouse."),
            ("Faith Seed", "Mark 10:29-30", "There is no man that hath left house, or brethren."),
            ("Covenant of Favour", "Psalm 5:12", "Thou wilt bless the righteous with favour."),
            ("Dominion Over Poverty", "Deuteronomy 28:47-48", "Because thou didst not serve the Lord with joyfulness."),
            ("The Anointing of Breakthrough", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Covenant of Divine Protection", "Psalm 91:11", "He shall give his angels charge over thee."),
            ("Faith for Healing", "Isaiah 53:5", "With his stripes we are healed."),
            ("The Power of Praise", "2 Chronicles 20:22", "When they began to sing and to praise."),
            ("Covenant of Increase", "Malachi 3:10", "I will pour you out a blessing."),
            ("Supernatural Wisdom", "James 1:5", "Let him ask of God, that giveth to all men liberally."),
            ("The Covenant of Peace", "Ezekiel 37:26", "I will make a covenant of peace with them."),
            ("Faith Patience", "Hebrews 6:12", "Be followers of them who through faith and patience inherit the promises."),
            ("Covenant of Success", "Joshua 1:8", "Meditate therein day and night."),
            ("The Power of Agreement", "Matthew 18:19", "If two of you shall agree on earth."),
            ("Dominion Over Darkness", "Colossians 1:13", "He hath delivered us from the power of darkness."),
            ("Covenant of Abundance", "3 John 1:2", "I wish that you may prosper and be in health."),
            ("Faith Declaration", "2 Corinthians 4:13", "I believed; therefore I have spoken."),
            ("The Anointing of Prosperity", "Deuteronomy 28:13", "The Lord shall make thee the head."),
            ("Covenant of Favour", "Psalm 30:5", "His favour is for life."),
            ("Supernatural Breakthrough", "Micah 2:13", "The breaker is come up before them."),
            ("The Power of Seeds", "Galatians 6:7", "Whatsoever a man soweth, that shall he also reap."),
            ("Covenant of Divine Health", "Isaiah 53:5", "By his stripes we are healed."),
            ("Faith Over Fear", "2 Timothy 1:7", "God hath not given us the spirit of fear."),
            ("Dominion Mandate", "Psalm 8:6", "Thou madest him to have dominion over the works of thy hands."),
            ("Covenant of Open Doors", "Revelation 3:8", "I have set before thee an open door."),
            ("The Power of Worship", "2 Chronicles 5:13", "The house was filled with a cloud."),
        ],
    },
    "cac": {
        "name": "Christ Apostolic Church", "pastor": "Various Pastors", "color": "#0000FF",
        "focus": "Prayer, blood of Jesus, Holy Spirit",
        "themes": [
            ("The Power of Prayer", "James 5:16", "The effectual fervent prayer of a righteous man availeth much."),
            ("The Blood of Jesus", "1 John 1:7", "The blood of Jesus Christ his Son cleanseth us from all sin."),
            ("The Holy Spirit's Power", "Acts 1:8", "Ye shall receive power, after that the Holy Ghost is come upon you."),
            ("Divine Provision", "Philippians 4:19", "My God shall supply all your need according to his riches in glory."),
            ("The Word of Power", "Isaiah 55:11", "So shall my word be that goeth forth out of my mouth."),
            ("The Anointing of God", "2 Corinthians 1:21-22", "He which stablisheth us with you in Christ, and hath anointed us, is God."),
            ("Eternal Hope", "Romans 8:24", "For we are saved by hope."),
            ("The Power of the Name", "Philippians 2:9-11", "God gave him a name which is above every name."),
            ("Healing Power", "Isaiah 53:5", "With his stripes we are healed."),
            ("The Holy Spirit's Guidance", "John 16:13", "He will guide you into all truth."),
            ("Prayer and Fasting", "Matthew 17:21", "This kind goeth not out but by prayer and fasting."),
            ("The Blood Covenant", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("Divine Direction", "Proverbs 3:5-6", "He shall direct thy paths."),
            ("The Power of Praise", "Psalm 150:6", "Let everything that hath breath praise the Lord."),
            ("Holy Spirit Baptism", "Acts 2:4", "They were all filled with the Holy Ghost."),
            ("Divine Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("The Anointing Breaks Yokes", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Prayer of Faith", "Mark 11:24", "What things soever ye desire, when ye pray, believe that ye receive them."),
            ("The Blood Speaks", "Hebrews 12:24", "The blood of sprinkling that speaketh better things."),
            ("Divine Healing", "Exodus 15:26", "I am the Lord that healeth thee."),
            ("The Power of Worship", "John 4:24", "Worship him in spirit and truth."),
            ("Holy Spirit Fire", "Acts 2:3", "Cloven tongues like as of fire."),
            ("Prayer Warrior", "Ephesians 6:18", "Praying always with all prayer and supplication."),
            ("The Blood of Sprinkling", "1 Peter 1:2", "Sprinkling of the blood of Jesus Christ."),
            ("Divine Restoration", "Joel 2:25", "I will restore to you the years that the locust hath eaten."),
            ("The Power of Agreement", "Matthew 18:19", "If two shall agree on earth."),
            ("Holy Spirit Baptism", "Matthew 3:11", "He shall baptize you with the Holy Ghost."),
            ("The Blood of the Lamb", "Revelation 7:14", "These are they which came out of great tribulation."),
            ("Divine Open Heavens", "Malachi 3:10", "I will open you the windows of heaven."),
            ("The Anointing of God", "Luke 4:18", "The Spirit of the Lord is upon me."),
            ("Prayer and Intercession", "Ezekiel 22:30", "I sought for a man to stand in the gap."),
            ("The Blood of Christ", "Hebrews 9:14", "How much more shall the blood of Christ cleanse your conscience."),
            ("Divine Breakthrough", "Micah 2:13", "The breaker is come up before them."),
            ("The Power of Decrees", "Job 22:28", "Thou shalt decree a thing, and it shall be established."),
            ("Holy Spirit Direction", "Acts 8:29", "The Spirit said unto Philip, Go near."),
            ("The Blood of Redemption", "Ephesians 1:7", "In him we have redemption through his blood."),
            ("Divine Favor", "Psalm 5:12", "Thou wilt bless the righteous with favour."),
            ("Prayer and Meditation", "Psalm 1:2", "On his law he meditates day and night."),
            ("The Power of Testimony", "Revelation 12:11", "They overcame by the word of their testimony."),
            ("Holy Spirit Comfort", "John 14:16", "He will give you another advocate."),
            ("The Blood of Jesus", "1 John 1:7", "The blood of Jesus cleanseth us from all sin."),
            ("Divine Provision", "Genesis 22:14", "The Lord will provide."),
            ("The Anointing of Breakthrough", "Isaiah 10:27", "The yoke shall be destroyed."),
            ("Prayer of Agreement", "Matthew 18:19", "If two of you agree on earth."),
            ("The Holy Spirit's Power", "Acts 1:8", "Ye shall receive power."),
            ("Divine Healing", "James 5:14", "Let them pray over him, anointing him with oil."),
            ("The Blood of the Covenant", "Matthew 26:28", "This is my blood of the new testament."),
            ("Divine Protection", "Psalm 91:11", "He shall give his angels charge over thee."),
            ("The Power of Worship", "2 Chronicles 5:13", "The house was filled with a cloud."),
            ("Holy Spirit Gift", "Acts 2:38", "Ye shall receive the gift of the Holy Ghost."),
        ],
    },
    "wcc": {
        "name": "Winners Chapel International", "pastor": "Bishop David Oyedepo", "color": "#008000",
        "focus": "Faith, covenant, dominion, praise",
        "themes": [
            ("The Power of Faith", "Hebrews 11:1", "Now faith is the substance of things hoped for."),
            ("The Covenant of Blessing", "Genesis 12:2", "I will make of thee a great nation, and I will bless thee."),
            ("Dominion Over Darkness", "Colossians 1:13", "Who hath delivered us from the power of darkness."),
            ("The Power of Praise", "Psalm 149:6", "Let the high praises of God be in their mouth."),
            ("Supernatural Increase", "Haggai 2:8", "The silver is mine, and the gold is mine."),
            ("The Word of Power", "Jeremiah 23:29", "Is not my word like as a fire? saith the Lord; and like a hammer."),
            ("The Blessing of Abraham", "Galatians 3:14", "That the blessing of Abraham might come on the Gentiles."),
            ("Faith for Victory", "1 John 5:4", "This is the victory that overcometh the world, even our faith."),
            ("Covenant of Prosperity", "Deuteronomy 28:2", "All these blessings shall come on thee."),
            ("Dominion Mandate", "Genesis 1:28", "Be fruitful, multiply, replenish the earth, and subdue it."),
            ("The Power of Worship", "2 Chronicles 20:22", "When they began to sing and to praise."),
            ("Faith Confession", "Romans 10:9-10", "If thou shalt confess with thy mouth the Lord Jesus."),
            ("Covenant of Open Heavens", "Malachi 3:10", "I will open you the windows of heaven."),
            ("The Anointing of Prosperity", "Deuteronomy 28:13", "The Lord shall make thee the head."),
            ("Praise as Warfare", "2 Chronicles 20:21", "When he had consulted with the people, he appointed singers."),
            ("Faith Action", "James 2:17", "Faith, if it hath not works, is dead."),
            ("Covenant of Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("Dominion Over Challenges", "Psalm 8:6", "Thou madest him to have dominion."),
            ("The Power of Seeds", "Galatians 6:7", "Whatsoever a man soweth, that shall he also reap."),
            ("Faith Patience", "Hebrews 6:12", "Through faith and patience inherit the promises."),
            ("Covenant of Healing", "Exodus 15:26", "I am the Lord that healeth thee."),
            ("Supernatural Breakthrough", "Micah 2:13", "The breaker is come up before them."),
            ("The Power of Agreement", "Matthew 18:19", "If two of you shall agree on earth."),
            ("Faith Declaration", "2 Corinthians 4:13", "I believed; therefore I have spoken."),
            ("Covenant of Favour", "Psalm 5:12", "Thou wilt bless the righteous with favour."),
            ("Dominion Over Darkness", "Ephesians 6:12", "We wrestle not against flesh and blood."),
            ("The Blessing of the Lord", "Proverbs 10:22", "The blessing of the Lord maketh rich."),
            ("Faith for Healing", "Isaiah 53:5", "With his stripes we are healed."),
            ("Covenant of Peace", "Ezekiel 37:26", "I will make a covenant of peace with them."),
            ("Praise and Worship", "Psalm 150:6", "Let everything that hath breath praise the Lord."),
            ("The Power of Tithing", "Malachi 3:10", "Bring ye all the tithes into the storehouse."),
            ("Faith Over Fear", "2 Timothy 1:7", "God hath not given us the spirit of fear."),
            ("Covenant of Increase", "Malachi 3:10", "I will pour you out a blessing."),
            ("Dominion in Prayer", "James 5:16", "The effectual fervent prayer availeth much."),
            ("The Anointing of God", "Luke 4:18", "The Spirit of the Lord is upon me."),
            ("Faith for Prosperity", "3 John 1:2", "I wish that you may prosper and be in health."),
            ("Covenant of Divine Direction", "Proverbs 3:5-6", "He shall direct thy paths."),
            ("Praise Breaks Chains", "Acts 16:25-26", "Paul and Silas prayed, and sang praises."),
            ("The Power of Worship", "John 4:24", "Worship him in spirit and truth."),
            ("Faith Seed", "Mark 10:29-30", "There is no man that hath left house."),
            ("Covenant of Restoration", "Joel 2:25", "I will restore to you the years."),
            ("Dominion Over Poverty", "Deuteronomy 28:47-48", "Because thou didst not serve the Lord."),
            ("The Power of Decrees", "Job 22:28", "Thou shalt decree a thing, and it shall be established."),
            ("Faith for Breakthrough", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Covenant of Abundance", "John 10:10", "Life more abundantly."),
            ("Praise as a Weapon", "2 Chronicles 20:22", "As they began to sing and praise."),
            ("The Anointing of Breakthrough", "Isaiah 10:27", "The yoke shall be destroyed."),
            ("Faith for Direction", "Proverbs 3:5-6", "In all thy ways acknowledge him."),
            ("Covenant of Open Doors", "Revelation 3:8", "I have set before thee an open door."),
            ("Dominion Mandate", "Genesis 1:28", "Subdue it and have dominion."),
        ],
    },
    "lagoschurch": {
        "name": "The Lord's Chosen Charismatic Revival Movement", "pastor": "Pastor Lazarus Muoka", "color": "#006400",
        "focus": "Chosen generation, healing, praise, victory",
        "themes": [
            ("The Chosen Generation", "1 Peter 2:9", "Ye are a chosen generation, a royal priesthood."),
            ("Divine Healing", "Isaiah 53:5", "With his stripes we are healed."),
            ("The Power of Praise", "Psalm 150:6", "Let everything that hath breath praise the Lord."),
            ("The Holy Communion", "1 Corinthians 11:24-25", "This is my body, which is broken for you."),
            ("Victory Over Temptation", "1 Corinthians 10:13", "God is faithful, who will not suffer you to be tempted above that ye are able."),
            ("The Second Coming", "Revelation 22:12", "Behold, I come quickly."),
            ("Eternal Life", "John 3:16", "Whosoever believeth in him should not perish, but have everlasting life."),
            ("Divine Protection", "Psalm 91:1", "He that dwelleth in the secret place of the most High."),
            ("The Blood of Jesus", "Revelation 12:11", "They overcame him by the blood of the Lamb."),
            ("The Power of Faith", "Mark 11:22", "Have faith in God."),
            ("Chosen by God", "Ephesians 1:4", "He hath chosen us in him before the foundation of the world."),
            ("Divine Breakthrough", "Micah 2:13", "The breaker is come up before them."),
            ("The Anointing", "Isaiah 10:27", "The yoke shall be destroyed because of the anointing."),
            ("Prayer and Fasting", "Matthew 17:21", "This kind goeth not out but by prayer and fasting."),
            ("The Power of Worship", "John 4:24", "Worship him in spirit and truth."),
            ("Divine Direction", "Proverbs 3:5-6", "He shall direct thy paths."),
            ("The Word of God", "Hebrews 4:12", "The word of God is quick and powerful."),
            ("Spiritual Warfare", "Ephesians 6:10-11", "Be strong in the Lord and in his mighty power."),
            ("Divine Provision", "Philippians 4:19", "My God shall supply all your need."),
            ("The Power of Praise", "2 Chronicles 20:22", "As they began to sing and to praise."),
            ("Chosen Generation", "1 Peter 2:9", "A peculiar people, that ye should show forth praises."),
            ("Divine Healing", "James 5:14", "Let them pray over him, anointing him with oil."),
            ("Victory in Christ", "Romans 8:37", "We are more than conquerors."),
            ("The Holy Spirit", "Acts 1:8", "Ye shall receive power when the Holy Ghost is come."),
            ("Eternal Hope", "Titus 2:13", "Looking for that blessed hope."),
            ("Divine Protection", "Psalm 91:11", "He shall give his angels charge over thee."),
            ("The Blood of the Lamb", "Hebrews 9:22", "Without shedding of blood is no remission."),
            ("Faith for Healing", "Mark 9:23", "All things are possible to him that believeth."),
            ("The Power of Worship", "Psalm 150:6", "Let everything praise the Lord."),
            ("Chosen by God", "John 15:16", "I have chosen you, and ordained you."),
            ("Divine Breakthrough", "Isaiah 10:27", "The yoke shall be destroyed."),
            ("The Anointing", "Luke 4:18", "The Spirit of the Lord is upon me."),
            ("Prayer and Worship", "Acts 16:25-26", "They prayed and sang praises."),
            ("The Word of Power", "Isaiah 55:11", "My word shall not return void."),
            ("Divine Direction", "Psalm 32:8", "I will instruct thee and teach thee."),
            ("The Power of Praise", "Acts 16:25-26", "The chains fell off."),
            ("Spiritual Authority", "Luke 10:19", "I give you power to tread on serpents."),
            ("Divine Provision", "Genesis 22:14", "The Lord will provide."),
            ("The Blood of Jesus", "1 John 1:7", "The blood cleanseth us from all sin."),
            ("Victory Over Sin", "Romans 6:14", "Sin shall not have dominion over you."),
            ("The Holy Spirit", "John 14:16", "He will give you another advocate."),
            ("Eternal Life", "John 17:3", "This is eternal life: that they know you."),
            ("Divine Healing", "Psalm 103:3", "Who healeth all thy diseases."),
            ("The Power of Faith", "Hebrews 11:1", "Faith is the substance of things hoped for."),
            ("Chosen Generation", "Revelation 1:6", "He hath made us kings and priests."),
            ("Divine Breakthrough", "Psalm 18:29", "By my God I have leaped over a wall."),
            ("The Anointing", "1 John 2:27", "The anointing which ye have received abideth in you."),
            ("Prayer of Faith", "James 5:15", "The prayer of faith shall save the sick."),
            ("The Word of God", "Psalm 119:105", "Thy word is a lamp to my feet."),
        ],
    },
}

def generate_reflection(day, title, focus):
    patterns = [
        f"In our {focus} tradition, {title.lower()} is a foundational truth. Today, the Lord invites you to experience this reality in a fresh way. Let His Word take root in your heart and produce lasting transformation.",
        f"The {focus} heritage teaches us that {title.lower()} is not merely a concept but a lived experience. As you meditate on this truth today, allow the Holy Spirit to make it real in your personal journey with God.",
        f"Within the {focus} community, we have seen the power of {title.lower()} demonstrated time and again. Today, position yourself to receive this truth anew. God is faithful to meet you where you are.",
        f"Scripture speaks clearly about {title.lower()}, and our {focus} tradition has always emphasized its importance. Today, let this truth renew your mind and strengthen your faith.",
        f"The {focus} faith has always valued {title.lower()} as essential for spiritual growth. Today, press into this truth with expectation. God rewards those who diligently seek Him.",
        f"In the spirit of {focus}, we embrace {title.lower()} as God's provision for every believer. Today, receive this truth with faith and watch God work in your situation.",
        f"Our {focus} heritage reminds us that {title.lower()} has sustained believers through every generation. Today, draw strength from this truth. The same God who was faithful then is faithful now.",
        f"The {focus} tradition calls us to live out {title.lower()} in practical ways. Today, ask the Holy Spirit to show you how this truth applies to your specific circumstances.",
        f"As part of the {focus} family, you have access to the power of {title.lower()}. Today, activate this truth in your life by faith.",
        f"Within the {focus} understanding, {title.lower()} reflects God's heart for His children. Today, align your life with this divine purpose and experience His blessings.",
        f"The {focus} community testifies to the reality of {title.lower()} in everyday life. Today, add your own testimony to this legacy of faith.",
        f"In the {focus} tradition, we recognize that {title.lower()} opens doors that no man can shut. Today, walk through those doors by faith.",
    ]
    return patterns[(day - 1) % len(patterns)]

def generate_prayer(day, title, focus):
    prayers = [
        f"Father, in Jesus name, I receive the fullness of {title.lower()} in my life today. Let Your {focus} power work mightily in me. Amen.",
        f"Lord, I thank You for {title.lower()}. Let this truth be established in my life today. I receive it by faith. In Jesus name, Amen.",
        f"God of our {focus} heritage, I decree {title.lower()} over my life today. Let every area experience Your transformative power. Amen.",
        f"Lord Jesus, I activate {title.lower()} in my life by faith. Let it manifest as a testimony of Your goodness. In Jesus name, Amen.",
        f"Father, I agree with Your Word concerning {title.lower()}. Let it be established in my life today. Amen.",
        f"Heavenly Father, I receive {title.lower()} by faith. Let it produce abundant fruit in my life. In Jesus name, Amen.",
        f"Lord, I thank You that {title.lower()} is my inheritance in Christ. I walk in it today. Amen.",
        f"God, I position myself to receive {title.lower()} today. Open my eyes to see Your hand at work. Amen.",
        f"Father, in agreement with my {focus} family, I receive {title.lower()} today. Let it be a reality. Amen.",
        f"Lord, I decree {title.lower()} over my family, my health, my finances. Let Your power be revealed. In Jesus name, Amen.",
        f"God of breakthrough, I receive {title.lower()} today. Let every barrier be removed. Amen.",
        f"Father, I thank You for {title.lower()}. Let it transform my life and bring glory to Your name. Amen.",
    ]
    return prayers[(day - 1) % len(prayers)]

def js_escape(s):
    return (s.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
            .replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t'))

def main():
    print("Church Devotional Generator")
    print("=" * 50)
    output_dir = os.path.join(os.path.dirname(__file__), '..', 'src', 'churchDevotionals')
    os.makedirs(output_dir, exist_ok=True)

    for key, config in DENOMINATIONS.items():
        print(f"\nGenerating {config['name']}...")
        filepath = os.path.join(output_dir, f"{key}.js")
        themes = config["themes"]
        focus = config["focus"]

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f'export const {key.upper()}_DEVOTIONALS = {{\n')
            f.write(f'  name: "{js_escape(config["name"])}",\n')
            f.write(f'  pastor: "{js_escape(config["pastor"])}",\n')
            f.write(f'  color: "{config["color"]}",\n')
            f.write('  devotionals: [\n')

            for day in range(1, 366):
                idx = (day - 1) % len(themes)
                title, verse, verse_text = themes[idx]
                text = generate_reflection(day, title, focus)
                prayer = generate_prayer(day, title, focus)
                f.write(f'    {{ day: {day}, title: "{js_escape(title)}", verse: "{js_escape(verse)}", verseText: "{js_escape(verse_text)}", text: "{js_escape(text)}", prayer: "{js_escape(prayer)}" }},\n')

            f.write('  ]\n};\n')

        print(f"  {config['name']}: 365 devotionals written")

    print(f"\nWriting index.js...")
    with open(os.path.join(output_dir, "index.js"), 'w', encoding='utf-8') as f:
        for key in DENOMINATIONS:
            f.write(f'import {{ {key.upper()}_DEVOTIONALS }} from "./{key}";\n')
        f.write('\nexport const CHURCH_DEVOTIONALS = {\n')
        for key in DENOMINATIONS:
            f.write(f'  "{key}": {key.upper()}_DEVOTIONALS,\n')
        f.write('};\n\nexport const CHURCH_NAMES = Object.keys(CHURCH_DEVOTIONALS);\n')

    print(f"  index.js written with {len(DENOMINATIONS)} denominations")
    print(f"\n{'=' * 50}")
    print(f"Total: {len(DENOMINATIONS) * 365} devotionals across {len(DENOMINATIONS)} denominations")

if __name__ == "__main__":
    main()
