export const CHURCH_DEVOTIONALS = {
  "Dunamis": {
    name: "Dunamis Gospel Church",
    pastor: "Pastor Paul Enenche",
    color: "#8B0000",
    devotionals: [
      { day: 1, title: "The Power of the Holy Spirit", verse: "Acts 1:8", verseText: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.", text: "The Holy Spirit is not just a force but a Person. He empowers believers for effective witness. Today, yield yourself to His leading. Let Him fill every area of your life with His supernatural power. When the Holy Spirit comes upon you, mediocrity gives way to excellence.", prayer: "Father, I receive the infilling of the Holy Spirit today. Let Your power rest upon me for effective witness in Jesus name." },
      { day: 2, title: "Walking in Divine Health", verse: "3 John 1:2", verseText: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.", text: "God's will for you is divine health. Sickness is not your portion. The same power that raised Christ from the dead dwells in you. Speak to your body today. Command every infirmity to leave. You are the temple of the Holy Spirit.", prayer: "Lord, I receive divine health today. I reject every sickness and disease. My body is the temple of the Holy Spirit in Jesus name." },
      { day: 3, title: "The Anointing Breaks Yokes", verse: "Isaiah 10:27", verseText: "And it shall come to pass in that day, that his burden shall be taken away from off thy shoulder, and his yoke from off thy neck, and the yoke shall be destroyed because of the anointing.", text: "The anointing of God is a burden-removing, yoke-destroying power. Whatever burden you carry today, the anointing of God will destroy it. The yoke of poverty, sickness, failure, and stagnation is broken today. Receive the anointing afresh.", prayer: "Father, let the anointing of the Holy Spirit destroy every yoke in my life today. I receive freedom and liberty in Jesus name." },
      { day: 4, title: "Financial Overflow", verse: "Deuteronomy 8:18", verseText: "But thou shalt remember the Lord thy God: for it is he that giveth thee power to get wealth.", text: "God is the source of your wealth. He gives you the power to create wealth. Do not rely on your own strength. Acknowledge Him in all your ways. He will direct your paths. Today, tap into the supernatural ability of God for financial breakthrough.", prayer: "Lord, I acknowledge You as my source. Give me the power to create wealth. Let financial overflow be my portion in Jesus name." },
      { day: 5, title: "Divine Direction", verse: "Proverbs 3:5-6", verseText: "Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", text: "God has a plan for your life. When you trust Him completely, He directs your steps. Do not lean on your own understanding. Today, commit your plans to the Lord. He will make your paths straight. His direction is perfect.", prayer: "Father, I trust You with my life. Direct my paths today. Let Your will prevail in every area of my life in Jesus name." },
      { day: 6, title: "Supernatural Signs", verse: "Mark 16:17", verseText: "And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues.", text: "Signs and wonders follow believers. You are not ordinary. The supernatural is your natural habitat. Today, expect signs and miracles. God will show Himself strong on your behalf. Believe and receive.", prayer: "Lord, let signs and wonders follow me today. Manifest Your power in my life in Jesus name." },
      { day: 7, title: "Restoration of All Things", verse: "Acts 3:21", verseText: "Whom the heaven must receive until the times of restitution of all things.", text: "God is a restorer. Whatever the enemy has stolen, God will restore. Your joy, peace, health, and prosperity are being restored today. The years the locusts have eaten are being restored. Believe in God's restoration power.", prayer: "Father, I receive total restoration today. Restore everything the enemy has stolen from me in Jesus name." }
    ]
  },
  "FCS": {
    name: "Fellowship of Christian Students",
    pastor: "FCS Leadership",
    color: "#006400",
    devotionals: [
      { day: 1, title: "Standing Firm in Faith", verse: "1 Corinthians 16:13", verseText: "Watch ye, stand fast in the faith, quit you like men, be strong.", text: "As students of Christ, we must stand firm in our faith. The world will present many challenges, but God's word is our anchor. Today, make a conscious decision to stand on the Word of God. Be strong and courageous.", prayer: "Lord, give me the strength to stand firm in faith. Help me to be courageous in my walk with You." },
      { day: 2, title: "Academic Excellence through Christ", verse: "Colossians 3:23", verseText: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", text: "Our studies are not just for ourselves but for God's glory. When we work heartily as unto the Lord, excellence follows. Today, commit your studies to God. He will give you wisdom and understanding.", prayer: "Father, I commit my studies to You. Grant me wisdom and understanding. Let me excel for Your glory." },
      { day: 3, title: "Peer Pressure and God's Standard", verse: "Romans 12:2", verseText: "And be not conformed to this world: but be ye transformed by the renewing of your mind.", text: "Peer pressure can lead us astray. But God calls us to be transformed, not conformed. Today, renew your mind with God's Word. Let His standard be your standard. You are called to be different.", prayer: "Lord, help me to resist peer pressure. Transform my mind with Your Word. Let me stand out for You." },
      { day: 4, title: "Prayer as Students", verse: "Philippians 4:6", verseText: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", text: "Prayer is our secret weapon as students. Instead of worrying, pray about everything. God hears and answers prayer. Today, bring your academic challenges to God in prayer. He will give you peace.", prayer: "Father, I bring all my academic challenges to You. Give me peace and direction in Jesus name." },
      { day: 5, title: "The Power of Fellowship", verse: "Hebrews 10:25", verseText: "Not forsaking the assembling of ourselves together.", text: "Fellowship with other believers strengthens our faith. We need each other. Today, connect with your FCS family. Encourage one another. Pray together. Study together. There is power in fellowship.", prayer: "Lord, bless our FCS fellowship. Help us to support and encourage one another in faith." },
      { day: 6, title: "Integrity in Academics", verse: "Proverbs 11:3", verseText: "The integrity of the upright shall guide them.", text: "Integrity is doing the right thing even when no one is watching. As Christian students, we must maintain integrity in our academics. No cheating, no compromise. God sees everything.", prayer: "Father, help me to walk in integrity. Let my academic work be pleasing to You." },
      { day: 7, title: "Purpose Beyond the Campus", verse: "Jeremiah 29:11", verseText: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.", text: "God has a purpose for your life beyond the campus. Your education is preparation for something greater. Today, trust God's plan for your future. He has thoughts of peace for you.", prayer: "Lord, reveal Your purpose for my life. Guide me to my destiny in Jesus name." }
    ]
  },
  "FoodForTheDay": {
    name: "Food for the Day",
    pastor: "Various Authors",
    color: "#FF8C00",
    devotionals: [
      { day: 1, title: "Daily Bread from Heaven", verse: "John 6:35", verseText: "And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger.", text: "Just as our bodies need daily food, our spirits need daily nourishment from God's Word. Today, feast on the bread of life. Let His Word be your sustenance. He satisfies every hunger of the soul.", prayer: "Lord, feed me with Your Word today. Satisfy my spiritual hunger. Let me never hunger for Your presence." },
      { day: 2, title: "Manna for Today", verse: "Exodus 16:4", verseText: "Then said the Lord unto Moses, Behold, I will rain bread from heaven for you.", text: "God provided manna daily for the Israelites. He provides for us daily too. Do not worry about tomorrow. Focus on today's provision. God is faithful. He will supply all your needs according to His riches in glory.", prayer: "Father, provide for my daily needs. Help me to trust You for today's manna." },
      { day: 3, title: "The Word as Food", verse: "Matthew 4:4", verseText: "Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.", text: "God's Word is more important than physical food. It nourishes our spirit and gives us life. Today, eat the Word of God. Meditate on it. Let it dwell in you richly. It is food for your soul.", prayer: "Lord, give me a hunger for Your Word. Let me feed on it daily for spiritual nourishment." },
      { day: 4, title: "Feeding Others", verse: "Matthew 25:35", verseText: "For I was an hungred, and ye gave me meat.", text: "When we feed others, we feed Jesus Himself. Today, look for someone to feed. Share the bread of life with someone. Share physical food with the needy. In doing so, you serve Christ.", prayer: "Father, give me the heart to feed others. Help me to share what You have given me." },
      { day: 5, title: "Spiritual Fasting", verse: "Isaiah 58:6", verseText: "Is not this the fast that I have chosen?", text: "Fasting is not just about food. It's about breaking chains and setting captives free. True fasting involves caring for the poor and oppressed. Today, consider a spiritual fast. Let your life be a blessing to others.", prayer: "Lord, teach me the true meaning of fasting. Help me to fast with purpose and compassion." },
      { day: 6, title: "Bread of Affliction", verse: "Psalm 127:2", verseText: "He giveth his beloved sleep.", text: "Sometimes life's bread comes with affliction. But God gives His beloved sleep. Even in hardship, God provides rest. Today, cast your cares on Him. He cares for you. Find rest in His presence.", prayer: "Father, give me rest in the midst of affliction. Help me to find peace in You." },
      { day: 7, title: "The Table of the Lord", verse: "Psalm 23:5", verseText: "Thou preparest a table before me in the presence of mine enemies.", text: "God prepares a table for us even in difficult times. Our enemies may surround us, but God's provision is abundant. Today, sit at the Lord's table. Enjoy His fellowship and provision.", prayer: "Lord, prepare a table for me today. Let me enjoy Your fellowship and provision." }
    ]
  },
  "DailyManna": {
    name: "Daily Manna",
    pastor: "Damilola Oyedepo",
    color: "#4169E1",
    devotionals: [
      { day: 1, title: "Walking with God", verse: "Amos 3:3", verseText: "Can two walk together, except they be agreed?", text: "Walking with God requires agreement with His Word. Today, align your will with God's will. When you walk with God, He directs your steps. He shows you the path of righteousness. Choose to walk with Him today.", prayer: "Lord, help me to walk with You in agreement. Let Your Word be my guide." },
      { day: 2, title: "The Power of Thanksgiving", verse: "Psalm 100:4", verseText: "Enter into his gates with thanksgiving, and into his courts with praise.", text: "Thanksgiving opens the gates of heaven. When we give thanks, we acknowledge God's goodness. Today, enter God's presence with thanksgiving. Let gratitude fill your heart. He inhabits the praises of His people.", prayer: "Father, I enter Your gates with thanksgiving. Receive my praise and gratitude today." },
      { day: 3, title: "Divine Favour", verse: "Psalm 5:12", verseText: "For thou, Lord, wilt bless the righteous; with favour wilt thou compass him as with a shield.", text: "God's favour surrounds the righteous like a shield. Today, walk in God's favour. It will open doors that no man can shut. It will make you a wonder to your generation. Receive divine favour today.", prayer: "Lord, let Your favour surround me today. Open doors of opportunity for me." },
      { day: 4, title: "Strength in Weakness", verse: "2 Corinthians 12:9", verseText: "My grace is sufficient for thee: for my strength is made perfect in weakness.", text: "When we are weak, God's strength is perfected in us. Today, surrender your weaknesses to God. His grace is sufficient. He will make His strength perfect in your weakness.", prayer: "Father, I surrender my weaknesses to You. Let Your strength be perfected in me." },
      { day: 5, title: "The Fear of the Lord", verse: "Proverbs 9:10", verseText: "The fear of the Lord is the beginning of wisdom.", text: "The fear of the Lord is the foundation of wisdom. Today, reverence God in all you do. Let His fear guide your decisions. When you fear God, you will lack no good thing.", prayer: "Lord, give me the fear of the Lord. Let it be the foundation of my wisdom." },
      { day: 6, title: "God's Faithfulness", verse: "Lamentations 3:22-23", verseText: "It is of the Lord's mercies that we are not consumed, because his compassions fail not. They are new every morning.", text: "God's faithfulness is new every morning. His mercies never fail. Today, trust in God's faithfulness. He will never leave you nor forsake you. His compassions are renewed for you today.", prayer: "Father, I trust in Your faithfulness. Your mercies are new every morning for me." },
      { day: 7, title: "The Joy of the Lord", verse: "Nehemiah 8:10", verseText: "The joy of the Lord is your strength.", text: "Joy is not dependent on circumstances. It comes from the Lord. Today, let the joy of the Lord be your strength. No matter what you face, His joy will sustain you. Rejoice in the Lord always.", prayer: "Lord, fill me with Your joy. Let it be my strength today and always." }
    ]
  },
  "BelieversLoveworld": {
    name: "Believers Loveworld (Christ Embassy)",
    pastor: "Pastor Chris Oyakhilome",
    color: "#FFD700",
    devotionals: [
      { day: 1, title: "You Are Born of the Word", verse: "1 Peter 1:23", verseText: "Being born again, not of corruptible seed, but of incorruptible, by the word of God.", text: "You are born of the Word of God, which lives and abides forever. This means the Word of God is your source and identity. Today, declare that you are a product of God's Word. Your life reflects His glory.", prayer: "Father, I thank You for making me born of Your Word. My life reflects Your glory today." },
      { day: 2, title: "The Spirit of God in You", verse: "1 Corinthians 3:16", verseText: "Know ye not that ye are the temple of God, and that the Spirit of God dwelleth in you?", text: "The Holy Spirit lives in you. You are not alone. His presence is your advantage. Today, acknowledge the Spirit of God in you. Let Him lead and guide you. He is your comforter and guide.", prayer: "Holy Spirit, I acknowledge Your presence in me. Lead me and guide me today." },
      { day: 3, title: "Walking in Love", verse: "1 John 4:8", verseText: "He that loveth not knoweth not God; for God is love.", text: "God is love, and He lives in you. Therefore, love is your nature. Today, walk in love. Let love be the motivation for everything you do. When you walk in love, you walk in God.", prayer: "Father, help me to walk in love today. Let Your love flow through me to others." },
      { day: 4, title: "The Power of Faith", verse: "Mark 11:22", verseText: "Have faith in God.", text: "Faith is your response to God's Word. When you have faith in God, mountains move. Today, exercise your faith. Speak to your situation. Declare God's Word over your life. Faith is the victory.", prayer: "Lord, I exercise my faith today. I speak to every mountain and command it to move." },
      { day: 5, title: "Your Identity in Christ", verse: "2 Corinthians 5:17", verseText: "Therefore if any man be in Christ, he is a new creature.", text: "You are a new creation in Christ. Old things have passed away. Today, see yourself as God sees you. You are righteous, holy, and redeemed. Walk in the consciousness of your new identity.", prayer: "Father, help me to see myself as You see me. I am a new creation in Christ." },
      { day: 6, title: "The Anointing of the Holy Spirit", verse: "Acts 10:38", verseText: "How God anointed Jesus of Nazareth with the Holy Ghost and with power.", text: "The same anointing that was upon Jesus is upon you. You are anointed to preach, to heal, to deliver. Today, walk in the anointing. It destroys every yoke of bondage.", prayer: "Lord, I walk in the anointing of the Holy Spirit. Let it destroy every yoke in my life." },
      { day: 7, title: "Glorifying God", verse: "1 Corinthians 10:31", verseText: "Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.", text: "Everything you do should glorify God. Your life is a testimony of His goodness. Today, live for His glory. Let your actions, words, and thoughts honor Him. He is worthy of all glory.", prayer: "Father, help me to live for Your glory today. Let everything I do honor You." }
    ]
  },
  "RCCG": {
    name: "Redeemed Christian Church of God",
    pastor: "Pastor E.A. Adeboye",
    color: "#FF0000",
    devotionals: [
      { day: 1, title: "Heavenly Blessings", verse: "Ephesians 1:3", verseText: "Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places.", text: "God has already blessed you with all spiritual blessings. They are yours in Christ Jesus. Today, access your blessings by faith. They are not in the future; they are in heavenly places, available now.", prayer: "Father, I access my spiritual blessings in heavenly places. They are mine in Christ Jesus." },
      { day: 2, title: "The Open Heavens", verse: "Malachi 3:10", verseText: "I will open you the windows of heaven, and pour you out a blessing.", text: "God promises open heavens over your life. When you are faithful in giving, He opens the windows of heaven. Today, expect an open heaven. God will pour out blessings you cannot contain.", prayer: "Lord, open the heavens over my life. Pour out blessings I cannot contain." },
      { day: 3, title: "Divine Protection", verse: "Psalm 91:1", verseText: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", text: "When you dwell in God's presence, you are under His protection. No weapon formed against you shall prosper. Today, abide under the shadow of the Almighty. He is your refuge and fortress.", prayer: "Father, I dwell in Your secret place. Be my refuge and fortress today." },
      { day: 4, title: "The Blood of Jesus", verse: "Revelation 12:11", verseText: "And they overcame him by the blood of the Lamb.", text: "The blood of Jesus is your weapon of victory. It speaks better things than the blood of Abel. Today, plead the blood of Jesus over your life, family, and circumstances. It overcomes every attack of the enemy.", prayer: "Lord, I plead the blood of Jesus over my life. I overcome every attack of the enemy." },
      { day: 5, title: "Restoration", verse: "Joel 2:25", verseText: "I will restore to you the years that the locust hath eaten.", text: "God is a restorer. Whatever you have lost, He will restore. The years the locusts have eaten are being restored today. Believe in God's restoration power. He will make all things new.", prayer: "Father, I receive total restoration. Restore everything the enemy has stolen." },
      { day: 6, title: "The Holy Spirit's Guidance", verse: "John 16:13", verseText: "He will guide you into all truth.", text: "The Holy Spirit is your guide. He leads you into all truth. Today, listen to His voice. Follow His direction. He will show you things to come. Trust the Holy Spirit's guidance.", prayer: "Holy Spirit, guide me into all truth today. I follow Your leading." },
      { day: 7, title: "Victory in Christ", verse: "1 Corinthians 15:57", verseText: "But thanks be to God, which giveth us the victory.", text: "Victory is yours in Christ Jesus. You are more than a conqueror. Today, walk in victory. No circumstance is bigger than your God. He has given you the victory. Rejoice and be glad.", prayer: "Father, I thank You for the victory. I walk in triumph over every challenge." }
    ]
  },
  "MFM": {
    name: "Mountain of Fire and Miracles Ministries",
    pastor: "Dr. D.K. Olukoya",
    color: "#800080",
    devotionals: [
      { day: 1, title: "Prayer as a Weapon", verse: "Ephesians 6:18", verseText: "Praying always with all prayer and supplication in the Spirit.", text: "Prayer is your most powerful weapon. It is the spiritual兵器 against the forces of darkness. Today, engage in aggressive prayer. Pray in the Spirit. Let your prayer life be fire🔥. Mountains are moving today.", prayer: "Father, ignite my prayer life. Let my prayers be fire🔥 that consumes every enemy." },
      { day: 2, title: "Spiritual Warfare", verse: "2 Corinthians 10:4", verseText: "For the weapons of our warfare are not carnal.", text: "Our weapons are mighty through God. They pull down strongholds. Today, use your spiritual weapons. The blood of Jesus, the Word of God, and the name of Jesus are your weapons. Fight and win.", prayer: "Lord, empower me for spiritual warfare. Let me use Your weapons to defeat every enemy." },
      { day: 3, title: "Breaking Curses", verse: "Galatians 3:13", verseText: "Christ hath redeemed us from the curse of the law.", text: "Christ has redeemed you from every curse. No generational curse has power over you. Today, break free from every curse. The blood of Jesus breaks every curse. You are free indeed.", prayer: "Father, I break free from every curse by the blood of Jesus. I am redeemed." },
      { day: 4, title: "The Fire of God", verse: "Hebrews 12:29", verseText: "For our God is a consuming fire.", text: "God is a consuming fire🔥. His fire🔥 purifies and protects. Today, ask for God's fire🔥 to fall upon your life. Let it consume every impurity. Let it burn away every chaff. His fire🔥 is your protection.", prayer: "Lord, let Your fire🔥 fall upon me. Consume every impurity and protect me today." },
      { day: 5, title: "Deliverance from Evil", verse: "Psalm 91:3", verseText: "Surely he shall deliver thee from the snare of the fowler.", text: "God delivers from every snare of the enemy. No trap can hold you. Today, cry out for deliverance. God will set you free. He is your deliverer. No power of darkness can hold you captive.", prayer: "Father, deliver me from every snare of the enemy. Set me free today." },
      { day: 6, title: "The Anointing to Overcome", verse: "1 John 2:27", verseText: "But the anointing which ye have received of him abideth in you.", text: "The anointing of God is upon you. It teaches you all things. Today, rely on the anointing. It will help you overcome every challenge. The same anointing that was upon Jesus is upon you.", prayer: "Lord, I rely on the anointing within me. Help me to overcome every challenge." },
      { day: 7, title: "Miracles and Signs", verse: "Acts 2:22", verseText: "Jesus of Nazareth, a man approved of God among you by miracles and wonders.", text: "The same miracles that followed Jesus will follow you. You are approved of God. Today, expect miracles. God will do wonders in your life. Signs and wonders are your portion.", prayer: "Father, let miracles and wonders follow me today. Manifest Your power in my life." }
    ]
  },
  "DeeperLife": {
    name: "Deeper Life Bible Church",
    pastor: "Pastor W.F. Kumuyi",
    color: "#0000CD",
    devotionals: [
      { day: 1, title: "Holiness and Purity", verse: "Hebrews 12:14", verseText: "Follow peace with all men, and holiness, without which no man shall see the Lord.", text: "Holiness is not optional for the believer. It is the pathway to seeing God. Today, pursue holiness with all your heart. Let purity be your lifestyle. Without holiness, no one will see the Lord.", prayer: "Father, help me to pursue holiness. Let purity be my lifestyle today." },
      { day: 2, title: "The Power of the Blood", verse: "Leviticus 17:11", verseText: "For the life of the flesh is in the blood.", text: "The blood of Jesus gives life and power. It cleanses, heals, and protects. Today, apply the blood of Jesus to your life. Let it speak for you. The blood is your covenant of life.", prayer: "Lord, I apply the blood of Jesus to my life. Let it speak life and protection over me." },
      { day: 3, title: "Obedience to God", verse: "John 14:15", verseText: "If ye love me, keep my commandments.", text: "Obedience is the proof of love for God. When we obey His commandments, we show our love. Today, obey God's Word. Let obedience be your lifestyle. It unlocks blessings and favor.", prayer: "Father, help me to obey Your Word. Let obedience be my lifestyle today." },
      { day: 4, title: "The Word of God", verse: "Psalm 119:105", verseText: "Thy word is a lamp to my feet.", text: "God's Word is a lamp to our feet. It guides us in the path of righteousness. Today, let the Word of God be your guide. Meditate on it day and night. It will lead you to success.", prayer: "Lord, let Your Word be my guide. Lead me in the path of righteousness." },
      { day: 5, title: "Prayer and Fasting", verse: "Matthew 17:21", verseText: "Howbeit this kind goeth not out but by prayer and fasting.", text: "Some battles require prayer and fasting. Today, consider a prayer and fasting session. It breaks every chain. It destroys every yoke. When you pray and fast, heaven responds.", prayer: "Father, give me the grace to pray and fast. Let every chain be broken today." },
      { day: 6, title: "Spiritual Growth", verse: "2 Peter 3:18", verseText: "But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ.", text: "Spiritual growth is essential for every believer. Today, desire to grow in grace. Know God more deeply. Let your relationship with Him mature. Growth is the evidence of life.", prayer: "Lord, help me to grow in grace. Let my knowledge of You increase daily." },
      { day: 7, title: "Faithfulness in Service", verse: "Matthew 25:21", verseText: "Well done, thou good and faithful servant.", text: "God rewards faithfulness. Today, be faithful in your service to God. Let your work for Him be excellent. One day, you will hear: 'Well done, good and faithful servant.' Faithfulness is the key.", prayer: "Father, help me to be faithful in Your service. Let my work be pleasing to You." }
    ]
  },
  "LagosChurch": {
    name: "The Lord's Chosen Charismatic Revival Movement",
    pastor: "Pastor Lazarus Muoka",
    color: "#006400",
    devotionals: [
      { day: 1, title: "The Chosen Generation", verse: "1 Peter 2:9", verseText: "Ye are a chosen generation, a royal priesthood.", text: "You are chosen by God for a purpose. You are not ordinary. Today, walk in the consciousness of being chosen. God has a plan for your life. Embrace your identity as God's chosen.", prayer: "Father, I thank You for choosing me. Help me to walk in Your purpose for my life." },
      { day: 2, title: "Divine Healing", verse: "Isaiah 53:5", verseText: "With his stripes we are healed.", text: "Healing is the children's bread. By Jesus stripes, you are healed. Today, receive your healing. No sickness has the right to stay in your body. You are healed by the blood of Jesus.", prayer: "Lord, I receive my healing today. By Your stripes, I am healed." },
      { day: 3, title: "The Power of Praise", verse: "Psalm 150:6", verseText: "Let everything that hath breath praise the Lord.", text: "Praise is a weapon of warfare. When you praise God, He fights your battles. Today, lift your voice in praise. Let everything that breathes praise the Lord. Your praise will silence the enemy.", prayer: "Father, I praise You today. Let my praise silence every enemy in my life." },
      { day: 4, title: "The Holy Communion", verse: "1 Corinthians 11:24-25", verseText: "This is my body, which is broken for you.", text: "The Holy Communion is a memorial of Christ's sacrifice. When we partake, we remember His death and resurrection. Today, partake of the Holy Communion with reverence. It brings healing and protection.", prayer: "Lord, as I partake of the Holy Communion, let it bring healing and protection to my life." },
      { day: 5, title: "Victory Over Temptation", verse: "1 Corinthians 10:13", verseText: "God is faithful, who will not suffer you to be tempted above that ye are able.", text: "God will not allow more temptation than you can handle. He always provides a way of escape. Today, resist temptation with the Word of God. God is faithful. He will help you overcome.", prayer: "Father, help me to overcome temptation. Give me the strength to resist the enemy." },
      { day: 6, title: "The Second Coming", verse: "Revelation 22:12", verseText: "And, behold, I come quickly; and my reward is with me.", text: "Jesus is coming back soon. Are you ready? Today, live in expectation of His return. Let your life be an offering worthy of His coming. He brings His reward with Him.", prayer: "Lord, help me to live in expectation of Your return. Let my life be worthy of You." },
      { day: 7, title: "Eternal Life", verse: "John 3:16", verseText: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", text: "God's greatest gift is eternal life through Jesus Christ. Today, cherish this gift. Eternal life is not just about duration but quality of life with God. Walk in eternal life today.", prayer: "Father, thank You for the gift of eternal life. Help me to walk in its fullness today." }
    ]
  },
  "Winners": {
    name: "Living Faith Church (Winners Chapel)",
    pastor: "Bishop David Oyedepo",
    color: "#FFD700",
    devotionals: [
      { day: 1, title: "The Covenant of Prosperity", verse: "Deuteronomy 8:18", verseText: "Thou shalt remember the Lord thy God: for it is he that giveth thee power to get wealth.", text: "Prosperity is a covenant right for God's children. God gives you the power to create wealth. Today, engage the covenant. Tithe faithfully. Give generously. God will open the windows of heaven.", prayer: "Father, I engage the covenant of prosperity. Open the windows of heaven over my life." },
      { day: 2, title: "Faith that Moves Mountains", verse: "Matthew 17:20", verseText: "If ye have faith as a grain of mustard seed, ye shall say unto this mountain.", text: "Faith as small as a mustard seed can move mountains. Today, exercise your faith. Speak to your mountains. They must move by the word of your testimony. Faith is your advantage.", prayer: "Lord, I exercise my faith today. I speak to every mountain and command it to move." },
      { day: 3, title: "The Word as a Weapon", verse: "Hebrews 4:12", verseText: "For the word of God is quick, and powerful, and sharper than any twoedged sword.", text: "God's Word is your most powerful weapon. It is living and active. Today, use the Word of God against every challenge. It cuts through every obstacle. The Word never fails.", prayer: "Father, help me to use Your Word as a weapon. Let it cut through every obstacle in my life." },
      { day: 4, title: "Supernatural Breakthrough", verse: "Exodus 14:21", verseText: "And the Lord caused the sea to go back by a strong east wind.", text: "God specializes in supernatural breakthroughs. When there seems to be no way, He makes a way. Today, trust God for a supernatural breakthrough. He will divide the Red Sea before you.", prayer: "Lord, I trust You for a supernatural breakthrough. Make a way where there seems to be no way." },
      { day: 5, title: "The Anointing for Success", verse: "Zechariah 4:6", verseText: "Not by might, nor by power, but by my spirit, saith the Lord.", text: "Success comes not by human effort but by God's Spirit. Today, rely on the Holy Spirit. Let Him guide and direct you. His anointing will bring success in every area of your life.", prayer: "Father, I rely on Your Spirit for success. Let Your anointing guide me today." },
      { day: 6, title: "Dominion Over Challenges", verse: "Genesis 1:28", verseText: "And God blessed them, and said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it.", text: "God has given you dominion over all challenges. You are created to subdue and have dominion. Today, exercise your dominion. Take charge of your circumstances. You are more than a conqueror.", prayer: "Lord, help me to exercise dominion over every challenge. I take charge today." },
      { day: 7, title: "The Blessing of the Lord", verse: "Proverbs 10:22", verseText: "The blessing of the Lord, it maketh rich, and he addeth no sorrow with it.", text: "God's blessing brings true riches without sorrow. Today, walk in God's blessing. It will open doors. It will bring favor. The blessing of the Lord is upon your life.", prayer: "Father, let Your blessing rest upon me today. Let it bring true riches without sorrow." }
    ]
  },
  "CAC": {
    name: "Christ Apostolic Church",
    pastor: "Various Pastors",
    color: "#0000FF",
    devotionals: [
      { day: 1, title: "The Power of Prayer", verse: "James 5:16", verseText: "The effectual fervent prayer of a righteous man availeth much.", text: "Prayer is powerful and effective. When a righteous person prays, heaven responds. Today, pray with fervency. Your prayers will avail much. God hears and answers prayer.", prayer: "Father, let my prayers be effectual and fervent. Hear and answer me today." },
      { day: 2, title: "The Blood of Jesus", verse: "1 John 1:7", verseText: "The blood of Jesus Christ his Son cleanseth us from all sin.", text: "The blood of Jesus cleanses from all sin. No matter what you have done, His blood can wash you clean. Today, apply the blood of Jesus to your life. It cleanses and purifies.", prayer: "Lord, wash me clean with Your blood. I receive Your cleansing today." },
      { day: 3, title: "The Holy Spirit's Power", verse: "Acts 1:8", verseText: "But ye shall receive power, after that the Holy Ghost is come upon you.", text: "The Holy Spirit gives power for effective witness. Today, receive the power of the Holy Spirit. Let Him fill you afresh. His power will transform your life and ministry.", prayer: "Holy Spirit, fill me with Your power. Let me be an effective witness for Christ." },
      { day: 4, title: "Divine Provision", verse: "Philippians 4:19", verseText: "My God shall supply all your need according to his riches in glory.", text: "God supplies all your needs according to His riches in glory. Today, trust God for divine provision. He will supply all your needs. His resources are unlimited.", prayer: "Father, I trust You for divine provision. Supply all my needs today." },
      { day: 5, title: "The Word of Power", verse: "Isaiah 55:11", verseText: "So shall my word be that goeth forth out of my mouth.", text: "God's Word is powerful. When it goes forth, it accomplishes its purpose. Today, speak God's Word over your life. It will not return void. It will accomplish what God pleases.", prayer: "Lord, let Your Word accomplish its purpose in my life today." },
      { day: 6, title: "The Anointing of God", verse: "2 Corinthians 1:21-22", verseText: "Now he which stablisheth us with you in Christ, and hath anointed us, is God.", text: "God has anointed you. You are set apart for His purpose. Today, walk in the anointing. It will break every yoke. It will destroy every bondage. The anointing is your advantage.", prayer: "Father, I walk in the anointing You have given me. Let it break every yoke today." },
      { day: 7, title: "Eternal Hope", verse: "Romans 8:24", verseText: "For we are saved by hope.", text: "Our hope is in eternal salvation. Today, hold on to this hope. It anchors your soul. No matter what you face, eternal hope is yours. Jesus is coming back for you.", prayer: "Lord, help me to hold on to eternal hope. Let it anchor my soul today." }
    ]
  },
  "WCC": {
    name: "Winners Chapel International",
    pastor: "Bishop David Oyedepo",
    color: "#008000",
    devotionals: [
      { day: 1, title: "The Power of Faith", verse: "Hebrews 11:1", verseText: "Now faith is the substance of things hoped for.", text: "Faith is the foundation of our walk with God. It is the substance of things hoped for. Today, activate your faith. Believe God for the impossible. Faith makes the invisible visible.", prayer: "Father, increase my faith today. Help me to believe for the impossible." },
      { day: 2, title: "The Covenant of Blessing", verse: "Genesis 12:2", verseText: "And I will make of thee a great nation, and I will bless thee.", text: "God's covenant of blessing is upon your life. He will make you a blessing. Today, walk in the covenant. Be faithful in your giving. God will bless you abundantly.", prayer: "Lord, I walk in Your covenant of blessing. Let me be a blessing to others." },
      { day: 3, title: "Dominion Over Darkness", verse: "Colossians 1:13", verseText: "Who hath delivered us from the power of darkness.", text: "Christ has delivered us from the power of darkness. We are translated into His kingdom. Today, exercise your dominion over darkness. No evil has power over you.", prayer: "Father, I exercise dominion over darkness. No evil has power over me." },
      { day: 4, title: "The Power of Praise", verse: "Psalm 149:6", verseText: "Let the high praises of God be in their mouth.", text: "High praises are a weapon of warfare. When you praise God, He fights your battles. Today, lift high praises to God. Let your praise be a weapon against the enemy.", prayer: "Lord, I lift high praises to You. Fight my battles through my praise today." },
      { day: 5, title: "Supernatural Increase", verse: "Haggai 2:8", verseText: "The silver is mine, and the gold is mine, saith the Lord.", text: "All resources belong to God. Today, trust Him for supernatural increase. He will multiply your resources. The gold and silver are His. He will supply your needs abundantly.", prayer: "Father, I trust You for supernatural increase. Multiply my resources today." },
      { day: 6, title: "The Word of Power", verse: "Jeremiah 23:29", verseText: "Is not my word like as a fire? saith the Lord; and like a hammer.", text: "God's Word is fire and hammer. It burns and breaks. Today, speak God's Word over your life. It will burn away impurities. It will break every chain. The Word is powerful.", prayer: "Lord, let Your Word burn and break in my life today." },
      { day: 7, title: "The Blessing of Abraham", verse: "Galatians 3:14", verseText: "That the blessing of Abraham might come on the Gentiles.", text: "The blessing of Abraham is yours in Christ. You are blessed with Abraham's blessings. Today, walk in this blessing. It includes prosperity, health, and favor. The blessing is yours.", prayer: "Father, I walk in the blessing of Abraham. Let it manifest in my life today." }
    ]
  }
};

export const CHURCH_NAMES = Object.keys(CHURCH_DEVOTIONALS);
