export const BIBLE_BOOKS = [
  { id: "Genesis", chapters: 50, testament: "OT" },
  { id: "Exodus", chapters: 40, testament: "OT" },
  { id: "Leviticus", chapters: 27, testament: "OT" },
  { id: "Numbers", chapters: 36, testament: "OT" },
  { id: "Deuteronomy", chapters: 34, testament: "OT" },
  { id: "Joshua", chapters: 24, testament: "OT" },
  { id: "Judges", chapters: 21, testament: "OT" },
  { id: "Ruth", chapters: 4, testament: "OT" },
  { id: "1 Samuel", chapters: 31, testament: "OT" },
  { id: "2 Samuel", chapters: 24, testament: "OT" },
  { id: "1 Kings", chapters: 22, testament: "OT" },
  { id: "2 Kings", chapters: 25, testament: "OT" },
  { id: "1 Chronicles", chapters: 29, testament: "OT" },
  { id: "2 Chronicles", chapters: 36, testament: "OT" },
  { id: "Ezra", chapters: 10, testament: "OT" },
  { id: "Nehemiah", chapters: 13, testament: "OT" },
  { id: "Esther", chapters: 10, testament: "OT" },
  { id: "Job", chapters: 42, testament: "OT" },
  { id: "Psalm", chapters: 150, testament: "OT" },
  { id: "Proverbs", chapters: 31, testament: "OT" },
  { id: "Ecclesiastes", chapters: 12, testament: "OT" },
  { id: "Song of Solomon", chapters: 8, testament: "OT" },
  { id: "Isaiah", chapters: 66, testament: "OT" },
  { id: "Jeremiah", chapters: 52, testament: "OT" },
  { id: "Lamentations", chapters: 5, testament: "OT" },
  { id: "Ezekiel", chapters: 48, testament: "OT" },
  { id: "Daniel", chapters: 12, testament: "OT" },
  { id: "Hosea", chapters: 14, testament: "OT" },
  { id: "Joel", chapters: 3, testament: "OT" },
  { id: "Amos", chapters: 9, testament: "OT" },
  { id: "Obadiah", chapters: 1, testament: "OT" },
  { id: "Jonah", chapters: 4, testament: "OT" },
  { id: "Micah", chapters: 7, testament: "OT" },
  { id: "Nahum", chapters: 3, testament: "OT" },
  { id: "Habakkuk", chapters: 3, testament: "OT" },
  { id: "Zephaniah", chapters: 3, testament: "OT" },
  { id: "Haggai", chapters: 2, testament: "OT" },
  { id: "Zechariah", chapters: 14, testament: "OT" },
  { id: "Malachi", chapters: 4, testament: "OT" },
  { id: "Matthew", chapters: 28, testament: "NT" },
  { id: "Mark", chapters: 16, testament: "NT" },
  { id: "Luke", chapters: 24, testament: "NT" },
  { id: "John", chapters: 21, testament: "NT" },
  { id: "Acts", chapters: 28, testament: "NT" },
  { id: "Romans", chapters: 16, testament: "NT" },
  { id: "1 Corinthians", chapters: 16, testament: "NT" },
  { id: "2 Corinthians", chapters: 13, testament: "NT" },
  { id: "Galatians", chapters: 6, testament: "NT" },
  { id: "Ephesians", chapters: 6, testament: "NT" },
  { id: "Philippians", chapters: 4, testament: "NT" },
  { id: "Colossians", chapters: 4, testament: "NT" },
  { id: "1 Thessalonians", chapters: 5, testament: "NT" },
  { id: "2 Thessalonians", chapters: 3, testament: "NT" },
  { id: "1 Timothy", chapters: 6, testament: "NT" },
  { id: "2 Timothy", chapters: 4, testament: "NT" },
  { id: "Titus", chapters: 3, testament: "NT" },
  { id: "Philemon", chapters: 1, testament: "NT" },
  { id: "Hebrews", chapters: 13, testament: "NT" },
  { id: "James", chapters: 5, testament: "NT" },
  { id: "1 Peter", chapters: 5, testament: "NT" },
  { id: "2 Peter", chapters: 3, testament: "NT" },
  { id: "1 John", chapters: 5, testament: "NT" },
  { id: "2 John", chapters: 1, testament: "NT" },
  { id: "3 John", chapters: 1, testament: "NT" },
  { id: "Jude", chapters: 1, testament: "NT" },
  { id: "Revelation", chapters: 22, testament: "NT" },
]

export const BIBLE_VERSIONS = [
  // === English - Popular (from Bible.com / BibleGateway) ===
  { id: "KJV", name: "King James Version", category: "English", year: 1611 },
  { id: "NKJV", name: "New King James Version", category: "English", year: 1982 },
  { id: "NIV", name: "New International Version", category: "English", year: 2011 },
  { id: "ESV", name: "English Standard Version", category: "English", year: 2001 },
  { id: "NASB", name: "New American Standard Bible", category: "English", year: 2020 },
  { id: "NASB1995", name: "New American Standard Bible 1995", category: "English", year: 1995 },
  { id: "NLT", name: "New Living Translation", category: "English", year: 2015 },
  { id: "CSB", name: "Christian Standard Bible", category: "English", year: 2017 },
  { id: "HCSB", name: "Holman Christian Standard Bible", category: "English", year: 2009 },
  { id: "AMP", name: "Amplified Bible", category: "English", year: 2015 },
  { id: "ASV", name: "American Standard Version", category: "English", year: 1901 },
  { id: "RSV", name: "Revised Standard Version", category: "English", year: 1971 },
  { id: "NRSV", name: "New Revised Standard Version", category: "English", year: 1989 },
  { id: "NRSVue", name: "New Revised Standard Version Updated", category: "English", year: 2021 },
  { id: "GNB", name: "Good News Bible", category: "English", year: 1992 },
  { id: "WEB", name: "World English Bible", category: "English", year: 2000 },
  { id: "CEV", name: "Contemporary English Version", category: "English", year: 1995 },
  { id: "NET", name: "NET Bible", category: "English", year: 2005 },
  { id: "NEB", name: "New English Bible", category: "English", year: 1970 },
  { id: "REB", name: "Revised English Bible", category: "English", year: 1989 },
  { id: "ERV", name: "Easy-to-Read Version", category: "English", year: 1987 },
  { id: "WEBBE", name: "World English Bible British Edition", category: "English", year: 2000 },
  { id: "WNT", name: "Weymouth New Testament", category: "English", year: 1903 },
  { id: "YLT", name: "Young's Literal Translation", category: "English", year: 1898 },
  { id: "DBY", name: "Darby Bible", category: "English", year: 1890 },
  { id: "DRB", name: "Douay-Rheims Bible", category: "English", year: 1899 },
  { id: "Knox", name: "Knox Bible", category: "English", year: 1945 },
  { id: "Moffatt", name: "Moffatt Translation", category: "English", year: 1926 },
  { id: "Phillips", name: "J.B. Phillips New Testament", category: "English", year: 1972 },
  { id: "TLB", name: "The Living Bible", category: "English", year: 1971 },
  { id: "MSG", name: "The Message", category: "English", year: 2002 },
  { id: "NCV", name: "New Century Version", category: "English", year: 1987 },
  { id: "CEB", name: "Common English Bible", category: "English", year: 2011 },
  { id: "NJB", name: "New Jerusalem Bible", category: "English", year: 1985 },
  { id: "JB", name: "Jerusalem Bible", category: "English", year: 1966 },
  { id: "NAB", name: "New American Bible", category: "English", year: 2011 },
  { id: "NABRE", name: "New American Bible Revised Edition", category: "English", year: 2011 },
  { id: "RNJB", name: "Revised New Jerusalem Bible", category: "English", year: 2019 },
  { id: "MEV", name: "Modern English Version", category: "English", year: 2014 },
  { id: "LEB", name: "Lexham English Bible", category: "English", year: 2012 },
  { id: "TLV", name: "Tree of Life Version", category: "English", year: 2014 },
  { id: "RV", name: "Revised Version", category: "English", year: 1885 },
  { id: "LSV", name: "Literal Standard Version", category: "English", year: 2020 },
  { id: "BSB", name: "Berean Standard Bible", category: "English", year: 2020 },
  { id: "BLB", name: "Berean Literal Bible", category: "English", year: 2020 },
  { id: "BSB2", name: "Berean Study Bible", category: "English", year: 2016 },
  { id: "EHV", name: "Evangelical Heritage Version", category: "English", year: 2019 },
  { id: "ISV", name: "International Standard Version", category: "English", year: 2011 },
  { id: "TNIV", name: "Today's New International Version", category: "English", year: 2005 },
  { id: "NIrV", name: "New International Reader's Version", category: "English", year: 2014 },
  { id: "BBE", name: "Bible in Basic English", category: "English", year: 1949 },
  { id: "OEB-CW", name: "Open English Bible Commonwealth", category: "English", year: 2010 },
  { id: "OEB-US", name: "Open English Bible US", category: "English", year: 2010 },
  { id: "AKJV", name: "Authorized King James Version", category: "English", year: 1769 },
  { id: "Geneva", name: "Geneva Bible", category: "English", year: 1599 },
  { id: "Tyndale", name: "Tyndale Bible", category: "English", year: 1534 },
  { id: "WBT", name: "Webster Bible", category: "English", year: 1833 },
  { id: "Wycliffe", name: "Wycliffe Bible", category: "English", year: 1382 },
  { id: "KJV2000", name: "King James Version 2000", category: "English", year: 2000 },
  // === Hebrew ===
  { id: "WLC", name: "Westminster Leningrad Codex", category: "Hebrew", year: 0 },
  // === Greek ===
  { id: "TR", name: "Textus Receptus", category: "Greek", year: 0 },
  { id: "SBLGNT", name: "SBL Greek New Testament", category: "Greek", year: 2010 },
  { id: "LXX", name: "Septuagint", category: "Greek", year: 0 },
  // === Jewish ===
  { id: "JPS", name: "Jewish Publication Society 1917", category: "Jewish", year: 1917 },
  { id: "JPS1985", name: "Jewish Publication Society 1985", category: "Jewish", year: 1985 },
  { id: "HNV", name: "Hebrew Names Version", category: "Jewish", year: 0 },
  { id: "OJB", name: "Orthodox Jewish Bible", category: "Jewish", year: 0 },
  // === Latin ===
  { id: "Vulgate", name: "Latin Vulgate", category: "Latin", year: 0 },
  { id: "NovaVulgata", name: "Nova Vulgata", category: "Latin", year: 1979 },
  // === European Languages ===
  { id: "Luther", name: "Lutherbibel (German)", category: "European Languages", year: 0 },
  { id: "Segond", name: "Louis Segond (French)", category: "European Languages", year: 0 },
  { id: "RVR", name: "Reina-Valera (Spanish)", category: "European Languages", year: 0 },
  { id: "Dio", name: "Giovanni Diodati (Italian)", category: "European Languages", year: 0 },
  { id: "Almeida", name: "Almeida (Portuguese)", category: "European Languages", year: 0 },
  { id: "Synodal", name: "Russian Synodal Bible", category: "European Languages", year: 0 },
  { id: "DutchSV", name: "Statenvertaling (Dutch)", category: "European Languages", year: 0 },
  { id: "BKR", name: "Bible kralick\u00e1 (Czech)", category: "European Languages", year: 0 },
  { id: "RCCV", name: "Protestant Romanian Bible", category: "European Languages", year: 0 },
  // === African Languages ===
  { id: "Yoruba", name: "Bibeli Mimo (Yoruba)", category: "African Languages", year: 0 },
  { id: "Igbo", name: "Baibo Nso (Igbo)", category: "African Languages", year: 0 },
  { id: "Hausa", name: "Littafi Mai Tsarki (Hausa)", category: "African Languages", year: 0 },
  { id: "Swahili", name: "Biblia Takatifu (Swahili)", category: "African Languages", year: 0 },
  { id: "Zulu", name: "IBhayibheli Elingcwele (Zulu)", category: "African Languages", year: 0 },
  { id: "Afrikaans", name: "Bybel (Afrikaans)", category: "African Languages", year: 0 },
  { id: "Amharic", name: "Amharic Bible", category: "African Languages", year: 0 },
  // === Asian Languages ===
  { id: "Chinese", name: "Chinese Union Version", category: "Asian Languages", year: 0 },
  { id: "ChineseT", name: "Chinese Union Version Traditional", category: "Asian Languages", year: 0 },
  { id: "Japanese", name: "Japanese Bible Kougo-yaku", category: "Asian Languages", year: 0 },
  { id: "Korean", name: "Korean Bible Revised", category: "Asian Languages", year: 0 },
  { id: "Hindi", name: "Hindi Bible IRV", category: "Asian Languages", year: 0 },
  { id: "Tamil", name: "Tamil Bible UV", category: "Asian Languages", year: 0 },
  { id: "Indonesian", name: "Indonesian Bible TB", category: "Asian Languages", year: 0 },
  { id: "Vietnamese", name: "Vietnamese Bible 1934", category: "Asian Languages", year: 0 },
  { id: "Tagalog", name: "Tagalog Ang Biblia", category: "Asian Languages", year: 0 },
  { id: "Cherokee", name: "Cherokee New Testament", category: "Asian Languages", year: 0 },
]

export const BIBLE_API_DIRECT = {
  KJV: "kjv", WEB: "web", WEBBE: "webbe", ASV: "asv", BBE: "bbe",
  DBY: "darby", DRB: "dra", YLT: "ylt", "OEB-CW": "oeb-cw", "OEB-US": "oeb-us",
  Chinese: "cuv", Almeida: "almeida", Vulgate: "clementine", Synodal: "synodal",
  BKR: "bkr", RCCV: "rccv", Cherokee: "cherokee",
  AKJV: "kjv", WBT: "kjv", RV: "kjv",
}

export const BIBLE_BOOK_IDS = {
  "Genesis": "GEN", "Exodus": "EXO", "Leviticus": "LEV", "Numbers": "NUM",
  "Deuteronomy": "DEU", "Joshua": "JOS", "Judges": "JDG", "Ruth": "RUT",
  "1 Samuel": "1SA", "2 Samuel": "2SA", "1 Kings": "1KI", "2 Kings": "2KI",
  "1 Chronicles": "1CH", "2 Chronicles": "2CH", "Ezra": "EZR", "Nehemiah": "NEH",
  "Esther": "EST", "Job": "JOB", "Psalm": "PSA", "Proverbs": "PRO",
  "Ecclesiastes": "ECC", "Song of Solomon": "SNG", "Isaiah": "ISA", "Jeremiah": "JER",
  "Lamentations": "LAM", "Ezekiel": "EZK", "Daniel": "DAN", "Hosea": "HOS",
  "Joel": "JOL", "Amos": "AMO", "Obadiah": "OBA", "Jonah": "JON",
  "Micah": "MIC", "Nahum": "NAM", "Habakkuk": "HAB", "Zephaniah": "ZEP",
  "Haggai": "HAG", "Zechariah": "ZEC", "Malachi": "MAL", "Matthew": "MAT",
  "Mark": "MRK", "Luke": "LUK", "John": "JHN", "Acts": "ACT",
  "Romans": "ROM", "1 Corinthians": "1CO", "2 Corinthians": "2CO", "Galatians": "GAL",
  "Ephesians": "EPH", "Philippians": "PHP", "Colossians": "COL", "1 Thessalonians": "1TH",
  "2 Thessalonians": "2TH", "1 Timothy": "1TI", "2 Timothy": "2TI", "Titus": "TIT",
  "Philemon": "PHM", "Hebrews": "HEB", "James": "JAS", "1 Peter": "1PE",
  "2 Peter": "2PE", "1 John": "1JN", "2 John": "2JN", "3 John": "3JN",
  "Jude": "JUD", "Revelation": "REV"
}

export const MOODS = [
  { emoji: "\uD83D\uDE0A", label: "Joyful" },
  { emoji: "\uD83D\uDE42", label: "Grateful" },
  { emoji: "\uD83D\uDE10", label: "Peaceful" },
  { emoji: "\uD83D\uDE22", label: "Anxious" },
  { emoji: "\uD83D\uDE2D", label: "Struggling" },
]
